// SPDX-License-Identifier: MIT

// Generated by scripts/generate-country-data.mjs from countries-list,
// i18n-iso-countries, and libphonenumber-js. Do not edit by hand.

export const countryDataMeta = {
  "generated": true,
  "validated": true,
  "countryCount": 250,
  "phoneCountryCount": 243,
  "sources": {
    "countries": "countries-list@3.4.1",
    "iso": "i18n-iso-countries@7.14.0",
    "phone": "libphonenumber-js@1.13.11"
  }
} as const

export const countryData = [
  {
    "code": "af",
    "alpha2": "AF",
    "alpha3": "AFG",
    "numeric": "004",
    "name": "Afghanistan",
    "nativeName": "افغانستان",
    "aliases": [],
    "emoji": "🇦🇫",
    "callingCodes": [
      "+93"
    ],
    "continent": "AS",
    "capital": "Kabul",
    "currencies": [
      "AFN"
    ],
    "languages": [
      "ps",
      "fa",
      "uz",
      "tk"
    ]
  },
  {
    "code": "ax",
    "alpha2": "AX",
    "alpha3": "ALA",
    "numeric": "248",
    "name": "Aland",
    "nativeName": "Åland",
    "aliases": [],
    "emoji": "🇦🇽",
    "callingCodes": [
      "+358"
    ],
    "continent": "EU",
    "capital": "Mariehamn",
    "currencies": [
      "EUR"
    ],
    "languages": [
      "sv"
    ]
  },
  {
    "code": "al",
    "alpha2": "AL",
    "alpha3": "ALB",
    "numeric": "008",
    "name": "Albania",
    "nativeName": "Shqipëria",
    "aliases": [],
    "emoji": "🇦🇱",
    "callingCodes": [
      "+355"
    ],
    "continent": "EU",
    "capital": "Tirana",
    "currencies": [
      "ALL"
    ],
    "languages": [
      "sq"
    ]
  },
  {
    "code": "dz",
    "alpha2": "DZ",
    "alpha3": "DZA",
    "numeric": "012",
    "name": "Algeria",
    "nativeName": "الجزائر",
    "aliases": [],
    "emoji": "🇩🇿",
    "callingCodes": [
      "+213"
    ],
    "continent": "AF",
    "capital": "Algiers",
    "currencies": [
      "DZD"
    ],
    "languages": [
      "ar"
    ]
  },
  {
    "code": "as",
    "alpha2": "AS",
    "alpha3": "ASM",
    "numeric": "016",
    "name": "American Samoa",
    "nativeName": "American Samoa",
    "aliases": [],
    "emoji": "🇦🇸",
    "callingCodes": [
      "+1"
    ],
    "continent": "OC",
    "capital": "Pago Pago",
    "currencies": [
      "USD"
    ],
    "languages": [
      "en",
      "sm"
    ]
  },
  {
    "code": "ad",
    "alpha2": "AD",
    "alpha3": "AND",
    "numeric": "020",
    "name": "Andorra",
    "nativeName": "Andorra",
    "aliases": [],
    "emoji": "🇦🇩",
    "callingCodes": [
      "+376"
    ],
    "continent": "EU",
    "capital": "Andorra la Vella",
    "currencies": [
      "EUR"
    ],
    "languages": [
      "ca"
    ]
  },
  {
    "code": "ao",
    "alpha2": "AO",
    "alpha3": "AGO",
    "numeric": "024",
    "name": "Angola",
    "nativeName": "Angola",
    "aliases": [],
    "emoji": "🇦🇴",
    "callingCodes": [
      "+244"
    ],
    "continent": "AF",
    "capital": "Luanda",
    "currencies": [
      "AOA"
    ],
    "languages": [
      "pt"
    ]
  },
  {
    "code": "ai",
    "alpha2": "AI",
    "alpha3": "AIA",
    "numeric": "660",
    "name": "Anguilla",
    "nativeName": "Anguilla",
    "aliases": [],
    "emoji": "🇦🇮",
    "callingCodes": [
      "+1"
    ],
    "continent": "NA",
    "capital": "The Valley",
    "currencies": [
      "XCD"
    ],
    "languages": [
      "en"
    ]
  },
  {
    "code": "aq",
    "alpha2": "AQ",
    "alpha3": "ATA",
    "numeric": "010",
    "name": "Antarctica",
    "nativeName": "Antarctica",
    "aliases": [],
    "emoji": "🇦🇶",
    "callingCodes": [
      "+672"
    ],
    "continent": "AN",
    "capital": "",
    "currencies": [],
    "languages": []
  },
  {
    "code": "ag",
    "alpha2": "AG",
    "alpha3": "ATG",
    "numeric": "028",
    "name": "Antigua and Barbuda",
    "nativeName": "Antigua and Barbuda",
    "aliases": [],
    "emoji": "🇦🇬",
    "callingCodes": [
      "+1"
    ],
    "continent": "NA",
    "capital": "Saint John's",
    "currencies": [
      "XCD"
    ],
    "languages": [
      "en"
    ]
  },
  {
    "code": "ar",
    "alpha2": "AR",
    "alpha3": "ARG",
    "numeric": "032",
    "name": "Argentina",
    "nativeName": "Argentina",
    "aliases": [],
    "emoji": "🇦🇷",
    "callingCodes": [
      "+54"
    ],
    "continent": "SA",
    "capital": "Buenos Aires",
    "currencies": [
      "ARS"
    ],
    "languages": [
      "es",
      "gn"
    ]
  },
  {
    "code": "am",
    "alpha2": "AM",
    "alpha3": "ARM",
    "numeric": "051",
    "name": "Armenia",
    "nativeName": "Հայաստան",
    "aliases": [],
    "emoji": "🇦🇲",
    "callingCodes": [
      "+374"
    ],
    "continent": "AS",
    "capital": "Yerevan",
    "currencies": [
      "AMD"
    ],
    "languages": [
      "hy",
      "ru"
    ]
  },
  {
    "code": "aw",
    "alpha2": "AW",
    "alpha3": "ABW",
    "numeric": "533",
    "name": "Aruba",
    "nativeName": "Aruba",
    "aliases": [],
    "emoji": "🇦🇼",
    "callingCodes": [
      "+297"
    ],
    "continent": "NA",
    "capital": "Oranjestad",
    "currencies": [
      "AWG"
    ],
    "languages": [
      "nl",
      "pa"
    ]
  },
  {
    "code": "au",
    "alpha2": "AU",
    "alpha3": "AUS",
    "numeric": "036",
    "name": "Australia",
    "nativeName": "Australia",
    "aliases": [],
    "emoji": "🇦🇺",
    "callingCodes": [
      "+61"
    ],
    "continent": "OC",
    "capital": "Canberra",
    "currencies": [
      "AUD"
    ],
    "languages": [
      "en"
    ]
  },
  {
    "code": "at",
    "alpha2": "AT",
    "alpha3": "AUT",
    "numeric": "040",
    "name": "Austria",
    "nativeName": "Österreich",
    "aliases": [],
    "emoji": "🇦🇹",
    "callingCodes": [
      "+43"
    ],
    "continent": "EU",
    "capital": "Vienna",
    "currencies": [
      "EUR"
    ],
    "languages": [
      "de"
    ]
  },
  {
    "code": "az",
    "alpha2": "AZ",
    "alpha3": "AZE",
    "numeric": "031",
    "name": "Azerbaijan",
    "nativeName": "Azərbaycan",
    "aliases": [],
    "emoji": "🇦🇿",
    "callingCodes": [
      "+994"
    ],
    "continent": "AS",
    "capital": "Baku",
    "currencies": [
      "AZN"
    ],
    "languages": [
      "az"
    ]
  },
  {
    "code": "bs",
    "alpha2": "BS",
    "alpha3": "BHS",
    "numeric": "044",
    "name": "Bahamas",
    "nativeName": "Bahamas",
    "aliases": [],
    "emoji": "🇧🇸",
    "callingCodes": [
      "+1"
    ],
    "continent": "NA",
    "capital": "Nassau",
    "currencies": [
      "BSD"
    ],
    "languages": [
      "en"
    ]
  },
  {
    "code": "bh",
    "alpha2": "BH",
    "alpha3": "BHR",
    "numeric": "048",
    "name": "Bahrain",
    "nativeName": "‏البحرين",
    "aliases": [
      "Bahrein"
    ],
    "emoji": "🇧🇭",
    "callingCodes": [
      "+973"
    ],
    "continent": "AS",
    "capital": "Manama",
    "currencies": [
      "BHD"
    ],
    "languages": [
      "ar"
    ]
  },
  {
    "code": "bd",
    "alpha2": "BD",
    "alpha3": "BGD",
    "numeric": "050",
    "name": "Bangladesh",
    "nativeName": "Bangladesh",
    "aliases": [
      "East Pakistan"
    ],
    "emoji": "🇧🇩",
    "callingCodes": [
      "+880"
    ],
    "continent": "AS",
    "capital": "Dhaka",
    "currencies": [
      "BDT"
    ],
    "languages": [
      "bn"
    ]
  },
  {
    "code": "bb",
    "alpha2": "BB",
    "alpha3": "BRB",
    "numeric": "052",
    "name": "Barbados",
    "nativeName": "Barbados",
    "aliases": [],
    "emoji": "🇧🇧",
    "callingCodes": [
      "+1"
    ],
    "continent": "NA",
    "capital": "Bridgetown",
    "currencies": [
      "BBD"
    ],
    "languages": [
      "en"
    ]
  },
  {
    "code": "by",
    "alpha2": "BY",
    "alpha3": "BLR",
    "numeric": "112",
    "name": "Belarus",
    "nativeName": "Беларусь",
    "aliases": [
      "Byelorussia",
      "Belorussia"
    ],
    "emoji": "🇧🇾",
    "callingCodes": [
      "+375"
    ],
    "continent": "EU",
    "capital": "Minsk",
    "currencies": [
      "BYN"
    ],
    "languages": [
      "be",
      "ru"
    ]
  },
  {
    "code": "be",
    "alpha2": "BE",
    "alpha3": "BEL",
    "numeric": "056",
    "name": "Belgium",
    "nativeName": "België",
    "aliases": [],
    "emoji": "🇧🇪",
    "callingCodes": [
      "+32"
    ],
    "continent": "EU",
    "capital": "Brussels",
    "currencies": [
      "EUR"
    ],
    "languages": [
      "nl",
      "fr",
      "de"
    ]
  },
  {
    "code": "bz",
    "alpha2": "BZ",
    "alpha3": "BLZ",
    "numeric": "084",
    "name": "Belize",
    "nativeName": "Belize",
    "aliases": [
      "British Honduras"
    ],
    "emoji": "🇧🇿",
    "callingCodes": [
      "+501"
    ],
    "continent": "NA",
    "capital": "Belmopan",
    "currencies": [
      "BZD"
    ],
    "languages": [
      "en",
      "es"
    ]
  },
  {
    "code": "bj",
    "alpha2": "BJ",
    "alpha3": "BEN",
    "numeric": "204",
    "name": "Benin",
    "nativeName": "Bénin",
    "aliases": [
      "Dahomey"
    ],
    "emoji": "🇧🇯",
    "callingCodes": [
      "+229"
    ],
    "continent": "AF",
    "capital": "Porto-Novo",
    "currencies": [
      "XOF"
    ],
    "languages": [
      "fr"
    ]
  },
  {
    "code": "bm",
    "alpha2": "BM",
    "alpha3": "BMU",
    "numeric": "060",
    "name": "Bermuda",
    "nativeName": "Bermuda",
    "aliases": [],
    "emoji": "🇧🇲",
    "callingCodes": [
      "+1"
    ],
    "continent": "NA",
    "capital": "Hamilton",
    "currencies": [
      "BMD"
    ],
    "languages": [
      "en"
    ]
  },
  {
    "code": "bt",
    "alpha2": "BT",
    "alpha3": "BTN",
    "numeric": "064",
    "name": "Bhutan",
    "nativeName": "ʼbrug-yul",
    "aliases": [],
    "emoji": "🇧🇹",
    "callingCodes": [
      "+975"
    ],
    "continent": "AS",
    "capital": "Thimphu",
    "currencies": [
      "BTN",
      "INR"
    ],
    "languages": [
      "dz"
    ]
  },
  {
    "code": "bo",
    "alpha2": "BO",
    "alpha3": "BOL",
    "numeric": "068",
    "name": "Bolivia",
    "nativeName": "Bolivia",
    "aliases": [],
    "emoji": "🇧🇴",
    "callingCodes": [
      "+591"
    ],
    "continent": "SA",
    "capital": "Sucre",
    "currencies": [
      "BOB",
      "BOV"
    ],
    "languages": [
      "es",
      "ay",
      "qu"
    ]
  },
  {
    "code": "bq",
    "alpha2": "BQ",
    "alpha3": "BES",
    "numeric": "535",
    "name": "Bonaire",
    "nativeName": "Bonaire",
    "aliases": [],
    "emoji": "🇧🇶",
    "callingCodes": [
      "+599"
    ],
    "continent": "NA",
    "capital": "Kralendijk",
    "currencies": [
      "USD"
    ],
    "languages": [
      "nl"
    ]
  },
  {
    "code": "ba",
    "alpha2": "BA",
    "alpha3": "BIH",
    "numeric": "070",
    "name": "Bosnia and Herzegovina",
    "nativeName": "Bosna i Hercegovina",
    "aliases": [],
    "emoji": "🇧🇦",
    "callingCodes": [
      "+387"
    ],
    "continent": "EU",
    "capital": "Sarajevo",
    "currencies": [
      "BAM"
    ],
    "languages": [
      "bs",
      "hr",
      "sr"
    ]
  },
  {
    "code": "bw",
    "alpha2": "BW",
    "alpha3": "BWA",
    "numeric": "072",
    "name": "Botswana",
    "nativeName": "Botswana",
    "aliases": [
      "Bechuanaland"
    ],
    "emoji": "🇧🇼",
    "callingCodes": [
      "+267"
    ],
    "continent": "AF",
    "capital": "Gaborone",
    "currencies": [
      "BWP"
    ],
    "languages": [
      "en",
      "tn"
    ]
  },
  {
    "code": "bv",
    "alpha2": "BV",
    "alpha3": "BVT",
    "numeric": "074",
    "name": "Bouvet Island",
    "nativeName": "Bouvetøya",
    "aliases": [],
    "emoji": "🇧🇻",
    "callingCodes": [
      "+47"
    ],
    "continent": "AN",
    "capital": "",
    "currencies": [
      "NOK"
    ],
    "languages": [
      "no",
      "nb",
      "nn"
    ]
  },
  {
    "code": "br",
    "alpha2": "BR",
    "alpha3": "BRA",
    "numeric": "076",
    "name": "Brazil",
    "nativeName": "Brasil",
    "aliases": [],
    "emoji": "🇧🇷",
    "callingCodes": [
      "+55"
    ],
    "continent": "SA",
    "capital": "Brasília",
    "currencies": [
      "BRL"
    ],
    "languages": [
      "pt"
    ]
  },
  {
    "code": "io",
    "alpha2": "IO",
    "alpha3": "IOT",
    "numeric": "086",
    "name": "British Indian Ocean Territory",
    "nativeName": "British Indian Ocean Territory",
    "aliases": [],
    "emoji": "🇮🇴",
    "callingCodes": [
      "+246"
    ],
    "continent": "AS",
    "capital": "Diego Garcia",
    "currencies": [
      "USD"
    ],
    "languages": [
      "en"
    ]
  },
  {
    "code": "vg",
    "alpha2": "VG",
    "alpha3": "VGB",
    "numeric": "092",
    "name": "British Virgin Islands",
    "nativeName": "British Virgin Islands",
    "aliases": [],
    "emoji": "🇻🇬",
    "callingCodes": [
      "+1"
    ],
    "continent": "NA",
    "capital": "Road Town",
    "currencies": [
      "USD"
    ],
    "languages": [
      "en"
    ]
  },
  {
    "code": "bn",
    "alpha2": "BN",
    "alpha3": "BRN",
    "numeric": "096",
    "name": "Brunei",
    "nativeName": "Negara Brunei Darussalam",
    "aliases": [],
    "emoji": "🇧🇳",
    "callingCodes": [
      "+673"
    ],
    "continent": "AS",
    "capital": "Bandar Seri Begawan",
    "currencies": [
      "BND"
    ],
    "languages": [
      "ms"
    ]
  },
  {
    "code": "bg",
    "alpha2": "BG",
    "alpha3": "BGR",
    "numeric": "100",
    "name": "Bulgaria",
    "nativeName": "България",
    "aliases": [],
    "emoji": "🇧🇬",
    "callingCodes": [
      "+359"
    ],
    "continent": "EU",
    "capital": "Sofia",
    "currencies": [
      "EUR"
    ],
    "languages": [
      "bg"
    ]
  },
  {
    "code": "bf",
    "alpha2": "BF",
    "alpha3": "BFA",
    "numeric": "854",
    "name": "Burkina Faso",
    "nativeName": "Burkina Faso",
    "aliases": [
      "Upper Volta"
    ],
    "emoji": "🇧🇫",
    "callingCodes": [
      "+226"
    ],
    "continent": "AF",
    "capital": "Ouagadougou",
    "currencies": [
      "XOF"
    ],
    "languages": [
      "fr",
      "ff"
    ]
  },
  {
    "code": "bi",
    "alpha2": "BI",
    "alpha3": "BDI",
    "numeric": "108",
    "name": "Burundi",
    "nativeName": "Burundi",
    "aliases": [],
    "emoji": "🇧🇮",
    "callingCodes": [
      "+257"
    ],
    "continent": "AF",
    "capital": "Gitega",
    "currencies": [
      "BIF"
    ],
    "languages": [
      "fr",
      "rn"
    ]
  },
  {
    "code": "cv",
    "alpha2": "CV",
    "alpha3": "CPV",
    "numeric": "132",
    "name": "Cabo Verde",
    "nativeName": "Cabo Verde",
    "aliases": [
      "Cape Verde"
    ],
    "emoji": "🇨🇻",
    "callingCodes": [
      "+238"
    ],
    "continent": "AF",
    "capital": "Praia",
    "currencies": [
      "CVE"
    ],
    "languages": [
      "pt"
    ]
  },
  {
    "code": "kh",
    "alpha2": "KH",
    "alpha3": "KHM",
    "numeric": "116",
    "name": "Cambodia",
    "nativeName": "កម្ពុជា",
    "aliases": [
      "Kampuchea"
    ],
    "emoji": "🇰🇭",
    "callingCodes": [
      "+855"
    ],
    "continent": "AS",
    "capital": "Phnom Penh",
    "currencies": [
      "KHR"
    ],
    "languages": [
      "km"
    ]
  },
  {
    "code": "cm",
    "alpha2": "CM",
    "alpha3": "CMR",
    "numeric": "120",
    "name": "Cameroon",
    "nativeName": "Cameroon",
    "aliases": [],
    "emoji": "🇨🇲",
    "callingCodes": [
      "+237"
    ],
    "continent": "AF",
    "capital": "Yaoundé",
    "currencies": [
      "XAF"
    ],
    "languages": [
      "en",
      "fr"
    ]
  },
  {
    "code": "ca",
    "alpha2": "CA",
    "alpha3": "CAN",
    "numeric": "124",
    "name": "Canada",
    "nativeName": "Canada",
    "aliases": [],
    "emoji": "🇨🇦",
    "callingCodes": [
      "+1"
    ],
    "continent": "NA",
    "capital": "Ottawa",
    "currencies": [
      "CAD"
    ],
    "languages": [
      "en",
      "fr"
    ]
  },
  {
    "code": "ky",
    "alpha2": "KY",
    "alpha3": "CYM",
    "numeric": "136",
    "name": "Cayman Islands",
    "nativeName": "Cayman Islands",
    "aliases": [],
    "emoji": "🇰🇾",
    "callingCodes": [
      "+1"
    ],
    "continent": "NA",
    "capital": "George Town",
    "currencies": [
      "KYD"
    ],
    "languages": [
      "en"
    ]
  },
  {
    "code": "cf",
    "alpha2": "CF",
    "alpha3": "CAF",
    "numeric": "140",
    "name": "Central African Republic",
    "nativeName": "Ködörösêse tî Bêafrîka",
    "aliases": [
      "Ubangi-Shari"
    ],
    "emoji": "🇨🇫",
    "callingCodes": [
      "+236"
    ],
    "continent": "AF",
    "capital": "Bangui",
    "currencies": [
      "XAF"
    ],
    "languages": [
      "fr",
      "sg"
    ]
  },
  {
    "code": "td",
    "alpha2": "TD",
    "alpha3": "TCD",
    "numeric": "148",
    "name": "Chad",
    "nativeName": "Tchad",
    "aliases": [],
    "emoji": "🇹🇩",
    "callingCodes": [
      "+235"
    ],
    "continent": "AF",
    "capital": "N'Djamena",
    "currencies": [
      "XAF"
    ],
    "languages": [
      "fr",
      "ar"
    ]
  },
  {
    "code": "cl",
    "alpha2": "CL",
    "alpha3": "CHL",
    "numeric": "152",
    "name": "Chile",
    "nativeName": "Chile",
    "aliases": [],
    "emoji": "🇨🇱",
    "callingCodes": [
      "+56"
    ],
    "continent": "SA",
    "capital": "Santiago",
    "currencies": [
      "CLP",
      "CLF"
    ],
    "languages": [
      "es"
    ]
  },
  {
    "code": "cn",
    "alpha2": "CN",
    "alpha3": "CHN",
    "numeric": "156",
    "name": "China",
    "nativeName": "中国",
    "aliases": [],
    "emoji": "🇨🇳",
    "callingCodes": [
      "+86"
    ],
    "continent": "AS",
    "capital": "Beijing",
    "currencies": [
      "CNY"
    ],
    "languages": [
      "zh"
    ]
  },
  {
    "code": "cx",
    "alpha2": "CX",
    "alpha3": "CXR",
    "numeric": "162",
    "name": "Christmas Island",
    "nativeName": "Christmas Island",
    "aliases": [],
    "emoji": "🇨🇽",
    "callingCodes": [
      "+61"
    ],
    "continent": "AS",
    "capital": "Flying Fish Cove",
    "currencies": [
      "AUD"
    ],
    "languages": [
      "en"
    ]
  },
  {
    "code": "cc",
    "alpha2": "CC",
    "alpha3": "CCK",
    "numeric": "166",
    "name": "Cocos (Keeling) Islands",
    "nativeName": "Cocos (Keeling) Islands",
    "aliases": [],
    "emoji": "🇨🇨",
    "callingCodes": [
      "+61"
    ],
    "continent": "AS",
    "capital": "West Island",
    "currencies": [
      "AUD"
    ],
    "languages": [
      "en"
    ]
  },
  {
    "code": "co",
    "alpha2": "CO",
    "alpha3": "COL",
    "numeric": "170",
    "name": "Colombia",
    "nativeName": "Colombia",
    "aliases": [],
    "emoji": "🇨🇴",
    "callingCodes": [
      "+57"
    ],
    "continent": "SA",
    "capital": "Bogotá",
    "currencies": [
      "COP"
    ],
    "languages": [
      "es"
    ]
  },
  {
    "code": "km",
    "alpha2": "KM",
    "alpha3": "COM",
    "numeric": "174",
    "name": "Comoros",
    "nativeName": "Komori",
    "aliases": [],
    "emoji": "🇰🇲",
    "callingCodes": [
      "+269"
    ],
    "continent": "AF",
    "capital": "Moroni",
    "currencies": [
      "KMF"
    ],
    "languages": [
      "ar",
      "fr"
    ]
  },
  {
    "code": "ck",
    "alpha2": "CK",
    "alpha3": "COK",
    "numeric": "184",
    "name": "Cook Islands",
    "nativeName": "Cook Islands",
    "aliases": [],
    "emoji": "🇨🇰",
    "callingCodes": [
      "+682"
    ],
    "continent": "OC",
    "capital": "Avarua",
    "currencies": [
      "NZD"
    ],
    "languages": [
      "en"
    ]
  },
  {
    "code": "cr",
    "alpha2": "CR",
    "alpha3": "CRI",
    "numeric": "188",
    "name": "Costa Rica",
    "nativeName": "Costa Rica",
    "aliases": [],
    "emoji": "🇨🇷",
    "callingCodes": [
      "+506"
    ],
    "continent": "NA",
    "capital": "San José",
    "currencies": [
      "CRC"
    ],
    "languages": [
      "es"
    ]
  },
  {
    "code": "hr",
    "alpha2": "HR",
    "alpha3": "HRV",
    "numeric": "191",
    "name": "Croatia",
    "nativeName": "Hrvatska",
    "aliases": [],
    "emoji": "🇭🇷",
    "callingCodes": [
      "+385"
    ],
    "continent": "EU",
    "capital": "Zagreb",
    "currencies": [
      "EUR"
    ],
    "languages": [
      "hr"
    ]
  },
  {
    "code": "cu",
    "alpha2": "CU",
    "alpha3": "CUB",
    "numeric": "192",
    "name": "Cuba",
    "nativeName": "Cuba",
    "aliases": [],
    "emoji": "🇨🇺",
    "callingCodes": [
      "+53"
    ],
    "continent": "NA",
    "capital": "Havana",
    "currencies": [
      "CUP"
    ],
    "languages": [
      "es"
    ]
  },
  {
    "code": "cw",
    "alpha2": "CW",
    "alpha3": "CUW",
    "numeric": "531",
    "name": "Curacao",
    "nativeName": "Curaçao",
    "aliases": [],
    "emoji": "🇨🇼",
    "callingCodes": [
      "+599"
    ],
    "continent": "NA",
    "capital": "Willemstad",
    "currencies": [
      "XCG"
    ],
    "languages": [
      "nl",
      "pa",
      "en"
    ]
  },
  {
    "code": "cy",
    "alpha2": "CY",
    "alpha3": "CYP",
    "numeric": "196",
    "name": "Cyprus",
    "nativeName": "Κύπρος",
    "aliases": [],
    "emoji": "🇨🇾",
    "callingCodes": [
      "+357"
    ],
    "continent": "EU",
    "capital": "Nicosia",
    "currencies": [
      "EUR"
    ],
    "languages": [
      "el",
      "tr",
      "hy"
    ]
  },
  {
    "code": "cz",
    "alpha2": "CZ",
    "alpha3": "CZE",
    "numeric": "203",
    "name": "Czechia",
    "nativeName": "Česko",
    "aliases": [
      "Czech Republic",
      "Česká republika"
    ],
    "emoji": "🇨🇿",
    "callingCodes": [
      "+420"
    ],
    "continent": "EU",
    "capital": "Prague",
    "currencies": [
      "CZK"
    ],
    "languages": [
      "cs"
    ]
  },
  {
    "code": "cd",
    "alpha2": "CD",
    "alpha3": "COD",
    "numeric": "180",
    "name": "Democratic Republic of the Congo",
    "nativeName": "République démocratique du Congo",
    "aliases": [
      "Zaire",
      "Congo-Kinshasa",
      "DR Congo",
      "DRC"
    ],
    "emoji": "🇨🇩",
    "callingCodes": [
      "+243"
    ],
    "continent": "AF",
    "capital": "Kinshasa",
    "currencies": [
      "CDF"
    ],
    "languages": [
      "fr",
      "ln",
      "kg",
      "sw",
      "lu"
    ]
  },
  {
    "code": "dk",
    "alpha2": "DK",
    "alpha3": "DNK",
    "numeric": "208",
    "name": "Denmark",
    "nativeName": "Danmark",
    "aliases": [],
    "emoji": "🇩🇰",
    "callingCodes": [
      "+45"
    ],
    "continent": "EU",
    "capital": "Copenhagen",
    "currencies": [
      "DKK"
    ],
    "languages": [
      "da"
    ]
  },
  {
    "code": "dj",
    "alpha2": "DJ",
    "alpha3": "DJI",
    "numeric": "262",
    "name": "Djibouti",
    "nativeName": "Djibouti",
    "aliases": [],
    "emoji": "🇩🇯",
    "callingCodes": [
      "+253"
    ],
    "continent": "AF",
    "capital": "Djibouti",
    "currencies": [
      "DJF"
    ],
    "languages": [
      "fr",
      "ar"
    ]
  },
  {
    "code": "dm",
    "alpha2": "DM",
    "alpha3": "DMA",
    "numeric": "212",
    "name": "Dominica",
    "nativeName": "Dominica",
    "aliases": [],
    "emoji": "🇩🇲",
    "callingCodes": [
      "+1"
    ],
    "continent": "NA",
    "capital": "Roseau",
    "currencies": [
      "XCD"
    ],
    "languages": [
      "en"
    ]
  },
  {
    "code": "do",
    "alpha2": "DO",
    "alpha3": "DOM",
    "numeric": "214",
    "name": "Dominican Republic",
    "nativeName": "República Dominicana",
    "aliases": [],
    "emoji": "🇩🇴",
    "callingCodes": [
      "+1"
    ],
    "continent": "NA",
    "capital": "Santo Domingo",
    "currencies": [
      "DOP"
    ],
    "languages": [
      "es"
    ]
  },
  {
    "code": "tl",
    "alpha2": "TL",
    "alpha3": "TLS",
    "numeric": "626",
    "name": "East Timor",
    "nativeName": "Timor-Leste",
    "aliases": [],
    "emoji": "🇹🇱",
    "callingCodes": [
      "+670"
    ],
    "continent": "OC",
    "capital": "Dili",
    "currencies": [
      "USD"
    ],
    "languages": [
      "pt"
    ]
  },
  {
    "code": "ec",
    "alpha2": "EC",
    "alpha3": "ECU",
    "numeric": "218",
    "name": "Ecuador",
    "nativeName": "Ecuador",
    "aliases": [],
    "emoji": "🇪🇨",
    "callingCodes": [
      "+593"
    ],
    "continent": "SA",
    "capital": "Quito",
    "currencies": [
      "USD"
    ],
    "languages": [
      "es"
    ]
  },
  {
    "code": "eg",
    "alpha2": "EG",
    "alpha3": "EGY",
    "numeric": "818",
    "name": "Egypt",
    "nativeName": "مصر‎",
    "aliases": [],
    "emoji": "🇪🇬",
    "callingCodes": [
      "+20"
    ],
    "continent": "AF",
    "capital": "Cairo",
    "currencies": [
      "EGP"
    ],
    "languages": [
      "ar"
    ]
  },
  {
    "code": "sv",
    "alpha2": "SV",
    "alpha3": "SLV",
    "numeric": "222",
    "name": "El Salvador",
    "nativeName": "El Salvador",
    "aliases": [],
    "emoji": "🇸🇻",
    "callingCodes": [
      "+503"
    ],
    "continent": "NA",
    "capital": "San Salvador",
    "currencies": [
      "USD",
      "SVC"
    ],
    "languages": [
      "es"
    ]
  },
  {
    "code": "gq",
    "alpha2": "GQ",
    "alpha3": "GNQ",
    "numeric": "226",
    "name": "Equatorial Guinea",
    "nativeName": "Guinea Ecuatorial",
    "aliases": [],
    "emoji": "🇬🇶",
    "callingCodes": [
      "+240"
    ],
    "continent": "AF",
    "capital": "Malabo",
    "currencies": [
      "XAF"
    ],
    "languages": [
      "es",
      "fr"
    ]
  },
  {
    "code": "er",
    "alpha2": "ER",
    "alpha3": "ERI",
    "numeric": "232",
    "name": "Eritrea",
    "nativeName": "ኤርትራ",
    "aliases": [],
    "emoji": "🇪🇷",
    "callingCodes": [
      "+291"
    ],
    "continent": "AF",
    "capital": "Asmara",
    "currencies": [
      "ERN"
    ],
    "languages": [
      "ti",
      "ar",
      "en"
    ]
  },
  {
    "code": "ee",
    "alpha2": "EE",
    "alpha3": "EST",
    "numeric": "233",
    "name": "Estonia",
    "nativeName": "Eesti",
    "aliases": [],
    "emoji": "🇪🇪",
    "callingCodes": [
      "+372"
    ],
    "continent": "EU",
    "capital": "Tallinn",
    "currencies": [
      "EUR"
    ],
    "languages": [
      "et"
    ]
  },
  {
    "code": "sz",
    "alpha2": "SZ",
    "alpha3": "SWZ",
    "numeric": "748",
    "name": "Eswatini",
    "nativeName": "Eswatini",
    "aliases": [
      "Swaziland"
    ],
    "emoji": "🇸🇿",
    "callingCodes": [
      "+268"
    ],
    "continent": "AF",
    "capital": "Lobamba",
    "currencies": [
      "SZL"
    ],
    "languages": [
      "en",
      "ss"
    ]
  },
  {
    "code": "et",
    "alpha2": "ET",
    "alpha3": "ETH",
    "numeric": "231",
    "name": "Ethiopia",
    "nativeName": "ኢትዮጵያ",
    "aliases": [
      "Abyssinia"
    ],
    "emoji": "🇪🇹",
    "callingCodes": [
      "+251"
    ],
    "continent": "AF",
    "capital": "Addis Ababa",
    "currencies": [
      "ETB"
    ],
    "languages": [
      "am"
    ]
  },
  {
    "code": "fk",
    "alpha2": "FK",
    "alpha3": "FLK",
    "numeric": "238",
    "name": "Falkland Islands",
    "nativeName": "Falkland Islands",
    "aliases": [],
    "emoji": "🇫🇰",
    "callingCodes": [
      "+500"
    ],
    "continent": "SA",
    "capital": "Stanley",
    "currencies": [
      "FKP"
    ],
    "languages": [
      "en"
    ]
  },
  {
    "code": "fo",
    "alpha2": "FO",
    "alpha3": "FRO",
    "numeric": "234",
    "name": "Faroe Islands",
    "nativeName": "Føroyar",
    "aliases": [],
    "emoji": "🇫🇴",
    "callingCodes": [
      "+298"
    ],
    "continent": "EU",
    "capital": "Tórshavn",
    "currencies": [
      "DKK"
    ],
    "languages": [
      "fo"
    ]
  },
  {
    "code": "fj",
    "alpha2": "FJ",
    "alpha3": "FJI",
    "numeric": "242",
    "name": "Fiji",
    "nativeName": "Fiji",
    "aliases": [],
    "emoji": "🇫🇯",
    "callingCodes": [
      "+679"
    ],
    "continent": "OC",
    "capital": "Suva",
    "currencies": [
      "FJD"
    ],
    "languages": [
      "en",
      "fj",
      "hi",
      "ur"
    ]
  },
  {
    "code": "fi",
    "alpha2": "FI",
    "alpha3": "FIN",
    "numeric": "246",
    "name": "Finland",
    "nativeName": "Suomi",
    "aliases": [],
    "emoji": "🇫🇮",
    "callingCodes": [
      "+358"
    ],
    "continent": "EU",
    "capital": "Helsinki",
    "currencies": [
      "EUR"
    ],
    "languages": [
      "fi",
      "sv"
    ]
  },
  {
    "code": "fr",
    "alpha2": "FR",
    "alpha3": "FRA",
    "numeric": "250",
    "name": "France",
    "nativeName": "France",
    "aliases": [],
    "emoji": "🇫🇷",
    "callingCodes": [
      "+33"
    ],
    "continent": "EU",
    "capital": "Paris",
    "currencies": [
      "EUR"
    ],
    "languages": [
      "fr"
    ]
  },
  {
    "code": "gf",
    "alpha2": "GF",
    "alpha3": "GUF",
    "numeric": "254",
    "name": "French Guiana",
    "nativeName": "Guyane française",
    "aliases": [],
    "emoji": "🇬🇫",
    "callingCodes": [
      "+594"
    ],
    "continent": "SA",
    "capital": "Cayenne",
    "currencies": [
      "EUR"
    ],
    "languages": [
      "fr"
    ]
  },
  {
    "code": "pf",
    "alpha2": "PF",
    "alpha3": "PYF",
    "numeric": "258",
    "name": "French Polynesia",
    "nativeName": "Polynésie française",
    "aliases": [],
    "emoji": "🇵🇫",
    "callingCodes": [
      "+689"
    ],
    "continent": "OC",
    "capital": "Papeetē",
    "currencies": [
      "XPF"
    ],
    "languages": [
      "fr"
    ]
  },
  {
    "code": "tf",
    "alpha2": "TF",
    "alpha3": "ATF",
    "numeric": "260",
    "name": "French Southern Territories",
    "nativeName": "Territoire des Terres australes et antarctiques fr",
    "aliases": [],
    "emoji": "🇹🇫",
    "callingCodes": [
      "+262"
    ],
    "continent": "AN",
    "capital": "Port-aux-Français",
    "currencies": [
      "EUR"
    ],
    "languages": [
      "fr"
    ]
  },
  {
    "code": "ga",
    "alpha2": "GA",
    "alpha3": "GAB",
    "numeric": "266",
    "name": "Gabon",
    "nativeName": "Gabon",
    "aliases": [],
    "emoji": "🇬🇦",
    "callingCodes": [
      "+241"
    ],
    "continent": "AF",
    "capital": "Libreville",
    "currencies": [
      "XAF"
    ],
    "languages": [
      "fr"
    ]
  },
  {
    "code": "gm",
    "alpha2": "GM",
    "alpha3": "GMB",
    "numeric": "270",
    "name": "Gambia",
    "nativeName": "Gambia",
    "aliases": [],
    "emoji": "🇬🇲",
    "callingCodes": [
      "+220"
    ],
    "continent": "AF",
    "capital": "Banjul",
    "currencies": [
      "GMD"
    ],
    "languages": [
      "en"
    ]
  },
  {
    "code": "ge",
    "alpha2": "GE",
    "alpha3": "GEO",
    "numeric": "268",
    "name": "Georgia",
    "nativeName": "საქართველო",
    "aliases": [],
    "emoji": "🇬🇪",
    "callingCodes": [
      "+995"
    ],
    "continent": "AS",
    "capital": "Tbilisi",
    "currencies": [
      "GEL"
    ],
    "languages": [
      "ka"
    ]
  },
  {
    "code": "de",
    "alpha2": "DE",
    "alpha3": "DEU",
    "numeric": "276",
    "name": "Germany",
    "nativeName": "Deutschland",
    "aliases": [],
    "emoji": "🇩🇪",
    "callingCodes": [
      "+49"
    ],
    "continent": "EU",
    "capital": "Berlin",
    "currencies": [
      "EUR"
    ],
    "languages": [
      "de"
    ]
  },
  {
    "code": "gh",
    "alpha2": "GH",
    "alpha3": "GHA",
    "numeric": "288",
    "name": "Ghana",
    "nativeName": "Ghana",
    "aliases": [
      "Gold Coast"
    ],
    "emoji": "🇬🇭",
    "callingCodes": [
      "+233"
    ],
    "continent": "AF",
    "capital": "Accra",
    "currencies": [
      "GHS"
    ],
    "languages": [
      "en"
    ]
  },
  {
    "code": "gi",
    "alpha2": "GI",
    "alpha3": "GIB",
    "numeric": "292",
    "name": "Gibraltar",
    "nativeName": "Gibraltar",
    "aliases": [],
    "emoji": "🇬🇮",
    "callingCodes": [
      "+350"
    ],
    "continent": "EU",
    "capital": "Gibraltar",
    "currencies": [
      "GIP"
    ],
    "languages": [
      "en"
    ]
  },
  {
    "code": "gr",
    "alpha2": "GR",
    "alpha3": "GRC",
    "numeric": "300",
    "name": "Greece",
    "nativeName": "Ελλάδα",
    "aliases": [],
    "emoji": "🇬🇷",
    "callingCodes": [
      "+30"
    ],
    "continent": "EU",
    "capital": "Athens",
    "currencies": [
      "EUR"
    ],
    "languages": [
      "el"
    ]
  },
  {
    "code": "gl",
    "alpha2": "GL",
    "alpha3": "GRL",
    "numeric": "304",
    "name": "Greenland",
    "nativeName": "Kalaallit Nunaat",
    "aliases": [],
    "emoji": "🇬🇱",
    "callingCodes": [
      "+299"
    ],
    "continent": "NA",
    "capital": "Nuuk",
    "currencies": [
      "DKK"
    ],
    "languages": [
      "kl"
    ]
  },
  {
    "code": "gd",
    "alpha2": "GD",
    "alpha3": "GRD",
    "numeric": "308",
    "name": "Grenada",
    "nativeName": "Grenada",
    "aliases": [],
    "emoji": "🇬🇩",
    "callingCodes": [
      "+1"
    ],
    "continent": "NA",
    "capital": "St. George's",
    "currencies": [
      "XCD"
    ],
    "languages": [
      "en"
    ]
  },
  {
    "code": "gp",
    "alpha2": "GP",
    "alpha3": "GLP",
    "numeric": "312",
    "name": "Guadeloupe",
    "nativeName": "Guadeloupe",
    "aliases": [],
    "emoji": "🇬🇵",
    "callingCodes": [
      "+590"
    ],
    "continent": "NA",
    "capital": "Basse-Terre",
    "currencies": [
      "EUR"
    ],
    "languages": [
      "fr"
    ]
  },
  {
    "code": "gu",
    "alpha2": "GU",
    "alpha3": "GUM",
    "numeric": "316",
    "name": "Guam",
    "nativeName": "Guam",
    "aliases": [],
    "emoji": "🇬🇺",
    "callingCodes": [
      "+1"
    ],
    "continent": "OC",
    "capital": "Hagåtña",
    "currencies": [
      "USD"
    ],
    "languages": [
      "en",
      "ch",
      "es"
    ]
  },
  {
    "code": "gt",
    "alpha2": "GT",
    "alpha3": "GTM",
    "numeric": "320",
    "name": "Guatemala",
    "nativeName": "Guatemala",
    "aliases": [],
    "emoji": "🇬🇹",
    "callingCodes": [
      "+502"
    ],
    "continent": "NA",
    "capital": "Guatemala City",
    "currencies": [
      "GTQ"
    ],
    "languages": [
      "es"
    ]
  },
  {
    "code": "gg",
    "alpha2": "GG",
    "alpha3": "GGY",
    "numeric": "831",
    "name": "Guernsey",
    "nativeName": "Guernsey",
    "aliases": [],
    "emoji": "🇬🇬",
    "callingCodes": [
      "+44"
    ],
    "continent": "EU",
    "capital": "St. Peter Port",
    "currencies": [
      "GBP"
    ],
    "languages": [
      "en",
      "fr"
    ]
  },
  {
    "code": "gn",
    "alpha2": "GN",
    "alpha3": "GIN",
    "numeric": "324",
    "name": "Guinea",
    "nativeName": "Guinée",
    "aliases": [],
    "emoji": "🇬🇳",
    "callingCodes": [
      "+224"
    ],
    "continent": "AF",
    "capital": "Conakry",
    "currencies": [
      "GNF"
    ],
    "languages": [
      "fr",
      "ff"
    ]
  },
  {
    "code": "gw",
    "alpha2": "GW",
    "alpha3": "GNB",
    "numeric": "624",
    "name": "Guinea-Bissau",
    "nativeName": "Guiné-Bissau",
    "aliases": [
      "Portuguese Guinea"
    ],
    "emoji": "🇬🇼",
    "callingCodes": [
      "+245"
    ],
    "continent": "AF",
    "capital": "Bissau",
    "currencies": [
      "XOF"
    ],
    "languages": [
      "pt"
    ]
  },
  {
    "code": "gy",
    "alpha2": "GY",
    "alpha3": "GUY",
    "numeric": "328",
    "name": "Guyana",
    "nativeName": "Guyana",
    "aliases": [],
    "emoji": "🇬🇾",
    "callingCodes": [
      "+592"
    ],
    "continent": "SA",
    "capital": "Georgetown",
    "currencies": [
      "GYD"
    ],
    "languages": [
      "en"
    ]
  },
  {
    "code": "ht",
    "alpha2": "HT",
    "alpha3": "HTI",
    "numeric": "332",
    "name": "Haiti",
    "nativeName": "Haïti",
    "aliases": [],
    "emoji": "🇭🇹",
    "callingCodes": [
      "+509"
    ],
    "continent": "NA",
    "capital": "Port-au-Prince",
    "currencies": [
      "HTG",
      "USD"
    ],
    "languages": [
      "fr",
      "ht"
    ]
  },
  {
    "code": "hm",
    "alpha2": "HM",
    "alpha3": "HMD",
    "numeric": "334",
    "name": "Heard Island and McDonald Islands",
    "nativeName": "Heard Island and McDonald Islands",
    "aliases": [],
    "emoji": "🇭🇲",
    "callingCodes": [
      "+61"
    ],
    "continent": "AN",
    "capital": "",
    "currencies": [
      "AUD"
    ],
    "languages": [
      "en"
    ]
  },
  {
    "code": "hn",
    "alpha2": "HN",
    "alpha3": "HND",
    "numeric": "340",
    "name": "Honduras",
    "nativeName": "Honduras",
    "aliases": [],
    "emoji": "🇭🇳",
    "callingCodes": [
      "+504"
    ],
    "continent": "NA",
    "capital": "Tegucigalpa",
    "currencies": [
      "HNL"
    ],
    "languages": [
      "es"
    ]
  },
  {
    "code": "hk",
    "alpha2": "HK",
    "alpha3": "HKG",
    "numeric": "344",
    "name": "Hong Kong",
    "nativeName": "香港",
    "aliases": [],
    "emoji": "🇭🇰",
    "callingCodes": [
      "+852"
    ],
    "continent": "AS",
    "capital": "City of Victoria",
    "currencies": [
      "HKD"
    ],
    "languages": [
      "zh",
      "en"
    ]
  },
  {
    "code": "hu",
    "alpha2": "HU",
    "alpha3": "HUN",
    "numeric": "348",
    "name": "Hungary",
    "nativeName": "Magyarország",
    "aliases": [],
    "emoji": "🇭🇺",
    "callingCodes": [
      "+36"
    ],
    "continent": "EU",
    "capital": "Budapest",
    "currencies": [
      "HUF"
    ],
    "languages": [
      "hu"
    ]
  },
  {
    "code": "is",
    "alpha2": "IS",
    "alpha3": "ISL",
    "numeric": "352",
    "name": "Iceland",
    "nativeName": "Ísland",
    "aliases": [],
    "emoji": "🇮🇸",
    "callingCodes": [
      "+354"
    ],
    "continent": "EU",
    "capital": "Reykjavik",
    "currencies": [
      "ISK"
    ],
    "languages": [
      "is"
    ]
  },
  {
    "code": "in",
    "alpha2": "IN",
    "alpha3": "IND",
    "numeric": "356",
    "name": "India",
    "nativeName": "भारत",
    "aliases": [],
    "emoji": "🇮🇳",
    "callingCodes": [
      "+91"
    ],
    "continent": "AS",
    "capital": "New Delhi",
    "currencies": [
      "INR"
    ],
    "languages": [
      "hi",
      "en"
    ]
  },
  {
    "code": "id",
    "alpha2": "ID",
    "alpha3": "IDN",
    "numeric": "360",
    "name": "Indonesia",
    "nativeName": "Indonesia",
    "aliases": [
      "Dutch East Indies"
    ],
    "emoji": "🇮🇩",
    "callingCodes": [
      "+62"
    ],
    "continent": "AS",
    "capital": "Jakarta",
    "currencies": [
      "IDR"
    ],
    "languages": [
      "id"
    ]
  },
  {
    "code": "ir",
    "alpha2": "IR",
    "alpha3": "IRN",
    "numeric": "364",
    "name": "Iran",
    "nativeName": "ایران",
    "aliases": [
      "Persia"
    ],
    "emoji": "🇮🇷",
    "callingCodes": [
      "+98"
    ],
    "continent": "AS",
    "capital": "Tehran",
    "currencies": [
      "IRR"
    ],
    "languages": [
      "fa"
    ]
  },
  {
    "code": "iq",
    "alpha2": "IQ",
    "alpha3": "IRQ",
    "numeric": "368",
    "name": "Iraq",
    "nativeName": "العراق",
    "aliases": [],
    "emoji": "🇮🇶",
    "callingCodes": [
      "+964"
    ],
    "continent": "AS",
    "capital": "Baghdad",
    "currencies": [
      "IQD"
    ],
    "languages": [
      "ar",
      "ku"
    ]
  },
  {
    "code": "ie",
    "alpha2": "IE",
    "alpha3": "IRL",
    "numeric": "372",
    "name": "Ireland",
    "nativeName": "Éire",
    "aliases": [],
    "emoji": "🇮🇪",
    "callingCodes": [
      "+353"
    ],
    "continent": "EU",
    "capital": "Dublin",
    "currencies": [
      "EUR"
    ],
    "languages": [
      "ga",
      "en"
    ]
  },
  {
    "code": "im",
    "alpha2": "IM",
    "alpha3": "IMN",
    "numeric": "833",
    "name": "Isle of Man",
    "nativeName": "Isle of Man",
    "aliases": [],
    "emoji": "🇮🇲",
    "callingCodes": [
      "+44"
    ],
    "continent": "EU",
    "capital": "Douglas",
    "currencies": [
      "GBP"
    ],
    "languages": [
      "en",
      "gv"
    ]
  },
  {
    "code": "il",
    "alpha2": "IL",
    "alpha3": "ISR",
    "numeric": "376",
    "name": "Israel",
    "nativeName": "יִשְׂרָאֵל",
    "aliases": [],
    "emoji": "🇮🇱",
    "callingCodes": [
      "+972"
    ],
    "continent": "AS",
    "capital": "Jerusalem",
    "currencies": [
      "ILS"
    ],
    "languages": [
      "he",
      "ar"
    ]
  },
  {
    "code": "it",
    "alpha2": "IT",
    "alpha3": "ITA",
    "numeric": "380",
    "name": "Italy",
    "nativeName": "Italia",
    "aliases": [],
    "emoji": "🇮🇹",
    "callingCodes": [
      "+39"
    ],
    "continent": "EU",
    "capital": "Rome",
    "currencies": [
      "EUR"
    ],
    "languages": [
      "it"
    ]
  },
  {
    "code": "ci",
    "alpha2": "CI",
    "alpha3": "CIV",
    "numeric": "384",
    "name": "Ivory Coast",
    "nativeName": "Côte d'Ivoire",
    "aliases": [
      "Cote d'Ivoire"
    ],
    "emoji": "🇨🇮",
    "callingCodes": [
      "+225"
    ],
    "continent": "AF",
    "capital": "Yamoussoukro",
    "currencies": [
      "XOF"
    ],
    "languages": [
      "fr"
    ]
  },
  {
    "code": "jm",
    "alpha2": "JM",
    "alpha3": "JAM",
    "numeric": "388",
    "name": "Jamaica",
    "nativeName": "Jamaica",
    "aliases": [],
    "emoji": "🇯🇲",
    "callingCodes": [
      "+1"
    ],
    "continent": "NA",
    "capital": "Kingston",
    "currencies": [
      "JMD"
    ],
    "languages": [
      "en"
    ]
  },
  {
    "code": "jp",
    "alpha2": "JP",
    "alpha3": "JPN",
    "numeric": "392",
    "name": "Japan",
    "nativeName": "日本",
    "aliases": [],
    "emoji": "🇯🇵",
    "callingCodes": [
      "+81"
    ],
    "continent": "AS",
    "capital": "Tokyo",
    "currencies": [
      "JPY"
    ],
    "languages": [
      "ja"
    ]
  },
  {
    "code": "je",
    "alpha2": "JE",
    "alpha3": "JEY",
    "numeric": "832",
    "name": "Jersey",
    "nativeName": "Jersey",
    "aliases": [],
    "emoji": "🇯🇪",
    "callingCodes": [
      "+44"
    ],
    "continent": "EU",
    "capital": "Saint Helier",
    "currencies": [
      "GBP"
    ],
    "languages": [
      "en",
      "fr"
    ]
  },
  {
    "code": "jo",
    "alpha2": "JO",
    "alpha3": "JOR",
    "numeric": "400",
    "name": "Jordan",
    "nativeName": "الأردن",
    "aliases": [],
    "emoji": "🇯🇴",
    "callingCodes": [
      "+962"
    ],
    "continent": "AS",
    "capital": "Amman",
    "currencies": [
      "JOD"
    ],
    "languages": [
      "ar"
    ]
  },
  {
    "code": "kz",
    "alpha2": "KZ",
    "alpha3": "KAZ",
    "numeric": "398",
    "name": "Kazakhstan",
    "nativeName": "Қазақстан",
    "aliases": [],
    "emoji": "🇰🇿",
    "callingCodes": [
      "+7"
    ],
    "continent": "AS",
    "capital": "Astana",
    "currencies": [
      "KZT"
    ],
    "languages": [
      "kk",
      "ru"
    ]
  },
  {
    "code": "ke",
    "alpha2": "KE",
    "alpha3": "KEN",
    "numeric": "404",
    "name": "Kenya",
    "nativeName": "Kenya",
    "aliases": [],
    "emoji": "🇰🇪",
    "callingCodes": [
      "+254"
    ],
    "continent": "AF",
    "capital": "Nairobi",
    "currencies": [
      "KES"
    ],
    "languages": [
      "en",
      "sw"
    ]
  },
  {
    "code": "ki",
    "alpha2": "KI",
    "alpha3": "KIR",
    "numeric": "296",
    "name": "Kiribati",
    "nativeName": "Kiribati",
    "aliases": [
      "Gilbert Islands"
    ],
    "emoji": "🇰🇮",
    "callingCodes": [
      "+686"
    ],
    "continent": "OC",
    "capital": "South Tarawa",
    "currencies": [
      "AUD"
    ],
    "languages": [
      "en"
    ]
  },
  {
    "code": "xk",
    "alpha2": "XK",
    "alpha3": "XKK",
    "numeric": "983",
    "name": "Kosovo",
    "nativeName": "Republika e Kosovës",
    "aliases": [],
    "emoji": "🇽🇰",
    "callingCodes": [
      "+383"
    ],
    "continent": "EU",
    "capital": "Pristina",
    "currencies": [
      "EUR"
    ],
    "languages": [
      "sq",
      "sr"
    ]
  },
  {
    "code": "kw",
    "alpha2": "KW",
    "alpha3": "KWT",
    "numeric": "414",
    "name": "Kuwait",
    "nativeName": "الكويت",
    "aliases": [],
    "emoji": "🇰🇼",
    "callingCodes": [
      "+965"
    ],
    "continent": "AS",
    "capital": "Kuwait City",
    "currencies": [
      "KWD"
    ],
    "languages": [
      "ar"
    ]
  },
  {
    "code": "kg",
    "alpha2": "KG",
    "alpha3": "KGZ",
    "numeric": "417",
    "name": "Kyrgyzstan",
    "nativeName": "Кыргызстан",
    "aliases": [
      "Kirghizia",
      "Kyrgyz Republic"
    ],
    "emoji": "🇰🇬",
    "callingCodes": [
      "+996"
    ],
    "continent": "AS",
    "capital": "Bishkek",
    "currencies": [
      "KGS"
    ],
    "languages": [
      "ky",
      "ru"
    ]
  },
  {
    "code": "la",
    "alpha2": "LA",
    "alpha3": "LAO",
    "numeric": "418",
    "name": "Laos",
    "nativeName": "ສປປລາວ",
    "aliases": [
      "Lao PDR"
    ],
    "emoji": "🇱🇦",
    "callingCodes": [
      "+856"
    ],
    "continent": "AS",
    "capital": "Vientiane",
    "currencies": [
      "LAK"
    ],
    "languages": [
      "lo"
    ]
  },
  {
    "code": "lv",
    "alpha2": "LV",
    "alpha3": "LVA",
    "numeric": "428",
    "name": "Latvia",
    "nativeName": "Latvija",
    "aliases": [],
    "emoji": "🇱🇻",
    "callingCodes": [
      "+371"
    ],
    "continent": "EU",
    "capital": "Riga",
    "currencies": [
      "EUR"
    ],
    "languages": [
      "lv"
    ]
  },
  {
    "code": "lb",
    "alpha2": "LB",
    "alpha3": "LBN",
    "numeric": "422",
    "name": "Lebanon",
    "nativeName": "لبنان",
    "aliases": [],
    "emoji": "🇱🇧",
    "callingCodes": [
      "+961"
    ],
    "continent": "AS",
    "capital": "Beirut",
    "currencies": [
      "LBP"
    ],
    "languages": [
      "ar",
      "fr"
    ]
  },
  {
    "code": "ls",
    "alpha2": "LS",
    "alpha3": "LSO",
    "numeric": "426",
    "name": "Lesotho",
    "nativeName": "Lesotho",
    "aliases": [
      "Basutoland"
    ],
    "emoji": "🇱🇸",
    "callingCodes": [
      "+266"
    ],
    "continent": "AF",
    "capital": "Maseru",
    "currencies": [
      "LSL",
      "ZAR"
    ],
    "languages": [
      "en",
      "st"
    ]
  },
  {
    "code": "lr",
    "alpha2": "LR",
    "alpha3": "LBR",
    "numeric": "430",
    "name": "Liberia",
    "nativeName": "Liberia",
    "aliases": [],
    "emoji": "🇱🇷",
    "callingCodes": [
      "+231"
    ],
    "continent": "AF",
    "capital": "Monrovia",
    "currencies": [
      "LRD"
    ],
    "languages": [
      "en"
    ]
  },
  {
    "code": "ly",
    "alpha2": "LY",
    "alpha3": "LBY",
    "numeric": "434",
    "name": "Libya",
    "nativeName": "‏ليبيا",
    "aliases": [],
    "emoji": "🇱🇾",
    "callingCodes": [
      "+218"
    ],
    "continent": "AF",
    "capital": "Tripoli",
    "currencies": [
      "LYD"
    ],
    "languages": [
      "ar"
    ]
  },
  {
    "code": "li",
    "alpha2": "LI",
    "alpha3": "LIE",
    "numeric": "438",
    "name": "Liechtenstein",
    "nativeName": "Liechtenstein",
    "aliases": [],
    "emoji": "🇱🇮",
    "callingCodes": [
      "+423"
    ],
    "continent": "EU",
    "capital": "Vaduz",
    "currencies": [
      "CHF"
    ],
    "languages": [
      "de"
    ]
  },
  {
    "code": "lt",
    "alpha2": "LT",
    "alpha3": "LTU",
    "numeric": "440",
    "name": "Lithuania",
    "nativeName": "Lietuva",
    "aliases": [],
    "emoji": "🇱🇹",
    "callingCodes": [
      "+370"
    ],
    "continent": "EU",
    "capital": "Vilnius",
    "currencies": [
      "EUR"
    ],
    "languages": [
      "lt"
    ]
  },
  {
    "code": "lu",
    "alpha2": "LU",
    "alpha3": "LUX",
    "numeric": "442",
    "name": "Luxembourg",
    "nativeName": "Luxembourg",
    "aliases": [],
    "emoji": "🇱🇺",
    "callingCodes": [
      "+352"
    ],
    "continent": "EU",
    "capital": "Luxembourg",
    "currencies": [
      "EUR"
    ],
    "languages": [
      "fr",
      "de",
      "lb"
    ]
  },
  {
    "code": "mo",
    "alpha2": "MO",
    "alpha3": "MAC",
    "numeric": "446",
    "name": "Macao",
    "nativeName": "澳門",
    "aliases": [
      "Macau"
    ],
    "emoji": "🇲🇴",
    "callingCodes": [
      "+853"
    ],
    "continent": "AS",
    "capital": "",
    "currencies": [
      "MOP"
    ],
    "languages": [
      "zh",
      "pt"
    ]
  },
  {
    "code": "mg",
    "alpha2": "MG",
    "alpha3": "MDG",
    "numeric": "450",
    "name": "Madagascar",
    "nativeName": "Madagasikara",
    "aliases": [],
    "emoji": "🇲🇬",
    "callingCodes": [
      "+261"
    ],
    "continent": "AF",
    "capital": "Antananarivo",
    "currencies": [
      "MGA"
    ],
    "languages": [
      "fr",
      "mg"
    ]
  },
  {
    "code": "mw",
    "alpha2": "MW",
    "alpha3": "MWI",
    "numeric": "454",
    "name": "Malawi",
    "nativeName": "Malawi",
    "aliases": [
      "Nyasaland"
    ],
    "emoji": "🇲🇼",
    "callingCodes": [
      "+265"
    ],
    "continent": "AF",
    "capital": "Lilongwe",
    "currencies": [
      "MWK"
    ],
    "languages": [
      "en",
      "ny"
    ]
  },
  {
    "code": "my",
    "alpha2": "MY",
    "alpha3": "MYS",
    "numeric": "458",
    "name": "Malaysia",
    "nativeName": "Malaysia",
    "aliases": [],
    "emoji": "🇲🇾",
    "callingCodes": [
      "+60"
    ],
    "continent": "AS",
    "capital": "Kuala Lumpur",
    "currencies": [
      "MYR"
    ],
    "languages": [
      "ms"
    ]
  },
  {
    "code": "mv",
    "alpha2": "MV",
    "alpha3": "MDV",
    "numeric": "462",
    "name": "Maldives",
    "nativeName": "Maldives",
    "aliases": [],
    "emoji": "🇲🇻",
    "callingCodes": [
      "+960"
    ],
    "continent": "AS",
    "capital": "Malé",
    "currencies": [
      "MVR"
    ],
    "languages": [
      "dv"
    ]
  },
  {
    "code": "ml",
    "alpha2": "ML",
    "alpha3": "MLI",
    "numeric": "466",
    "name": "Mali",
    "nativeName": "Mali",
    "aliases": [
      "French Sudan"
    ],
    "emoji": "🇲🇱",
    "callingCodes": [
      "+223"
    ],
    "continent": "AF",
    "capital": "Bamako",
    "currencies": [
      "XOF"
    ],
    "languages": [
      "fr"
    ]
  },
  {
    "code": "mt",
    "alpha2": "MT",
    "alpha3": "MLT",
    "numeric": "470",
    "name": "Malta",
    "nativeName": "Malta",
    "aliases": [],
    "emoji": "🇲🇹",
    "callingCodes": [
      "+356"
    ],
    "continent": "EU",
    "capital": "Valletta",
    "currencies": [
      "EUR"
    ],
    "languages": [
      "mt",
      "en"
    ]
  },
  {
    "code": "mh",
    "alpha2": "MH",
    "alpha3": "MHL",
    "numeric": "584",
    "name": "Marshall Islands",
    "nativeName": "M̧ajeļ",
    "aliases": [],
    "emoji": "🇲🇭",
    "callingCodes": [
      "+692"
    ],
    "continent": "OC",
    "capital": "Majuro",
    "currencies": [
      "USD"
    ],
    "languages": [
      "en",
      "mh"
    ]
  },
  {
    "code": "mq",
    "alpha2": "MQ",
    "alpha3": "MTQ",
    "numeric": "474",
    "name": "Martinique",
    "nativeName": "Martinique",
    "aliases": [],
    "emoji": "🇲🇶",
    "callingCodes": [
      "+596"
    ],
    "continent": "NA",
    "capital": "Fort-de-France",
    "currencies": [
      "EUR"
    ],
    "languages": [
      "fr"
    ]
  },
  {
    "code": "mr",
    "alpha2": "MR",
    "alpha3": "MRT",
    "numeric": "478",
    "name": "Mauritania",
    "nativeName": "موريتانيا",
    "aliases": [],
    "emoji": "🇲🇷",
    "callingCodes": [
      "+222"
    ],
    "continent": "AF",
    "capital": "Nouakchott",
    "currencies": [
      "MRU"
    ],
    "languages": [
      "ar"
    ]
  },
  {
    "code": "mu",
    "alpha2": "MU",
    "alpha3": "MUS",
    "numeric": "480",
    "name": "Mauritius",
    "nativeName": "Maurice",
    "aliases": [],
    "emoji": "🇲🇺",
    "callingCodes": [
      "+230"
    ],
    "continent": "AF",
    "capital": "Port Louis",
    "currencies": [
      "MUR"
    ],
    "languages": [
      "en"
    ]
  },
  {
    "code": "yt",
    "alpha2": "YT",
    "alpha3": "MYT",
    "numeric": "175",
    "name": "Mayotte",
    "nativeName": "Mayotte",
    "aliases": [],
    "emoji": "🇾🇹",
    "callingCodes": [
      "+262"
    ],
    "continent": "AF",
    "capital": "Mamoudzou",
    "currencies": [
      "EUR"
    ],
    "languages": [
      "fr"
    ]
  },
  {
    "code": "mx",
    "alpha2": "MX",
    "alpha3": "MEX",
    "numeric": "484",
    "name": "Mexico",
    "nativeName": "México",
    "aliases": [],
    "emoji": "🇲🇽",
    "callingCodes": [
      "+52"
    ],
    "continent": "NA",
    "capital": "Mexico City",
    "currencies": [
      "MXN"
    ],
    "languages": [
      "es"
    ]
  },
  {
    "code": "fm",
    "alpha2": "FM",
    "alpha3": "FSM",
    "numeric": "583",
    "name": "Micronesia",
    "nativeName": "Micronesia",
    "aliases": [],
    "emoji": "🇫🇲",
    "callingCodes": [
      "+691"
    ],
    "continent": "OC",
    "capital": "Palikir",
    "currencies": [
      "USD"
    ],
    "languages": [
      "en"
    ]
  },
  {
    "code": "md",
    "alpha2": "MD",
    "alpha3": "MDA",
    "numeric": "498",
    "name": "Moldova",
    "nativeName": "Moldova",
    "aliases": [
      "Moldavia"
    ],
    "emoji": "🇲🇩",
    "callingCodes": [
      "+373"
    ],
    "continent": "EU",
    "capital": "Chișinău",
    "currencies": [
      "MDL"
    ],
    "languages": [
      "ro"
    ]
  },
  {
    "code": "mc",
    "alpha2": "MC",
    "alpha3": "MCO",
    "numeric": "492",
    "name": "Monaco",
    "nativeName": "Monaco",
    "aliases": [],
    "emoji": "🇲🇨",
    "callingCodes": [
      "+377"
    ],
    "continent": "EU",
    "capital": "Monaco",
    "currencies": [
      "EUR"
    ],
    "languages": [
      "fr"
    ]
  },
  {
    "code": "mn",
    "alpha2": "MN",
    "alpha3": "MNG",
    "numeric": "496",
    "name": "Mongolia",
    "nativeName": "Монгол улс",
    "aliases": [],
    "emoji": "🇲🇳",
    "callingCodes": [
      "+976"
    ],
    "continent": "AS",
    "capital": "Ulan Bator",
    "currencies": [
      "MNT"
    ],
    "languages": [
      "mn"
    ]
  },
  {
    "code": "me",
    "alpha2": "ME",
    "alpha3": "MNE",
    "numeric": "499",
    "name": "Montenegro",
    "nativeName": "Црна Гора",
    "aliases": [],
    "emoji": "🇲🇪",
    "callingCodes": [
      "+382"
    ],
    "continent": "EU",
    "capital": "Podgorica",
    "currencies": [
      "EUR"
    ],
    "languages": [
      "sr",
      "bs",
      "sq",
      "hr"
    ]
  },
  {
    "code": "ms",
    "alpha2": "MS",
    "alpha3": "MSR",
    "numeric": "500",
    "name": "Montserrat",
    "nativeName": "Montserrat",
    "aliases": [],
    "emoji": "🇲🇸",
    "callingCodes": [
      "+1"
    ],
    "continent": "NA",
    "capital": "Plymouth",
    "currencies": [
      "XCD"
    ],
    "languages": [
      "en"
    ]
  },
  {
    "code": "ma",
    "alpha2": "MA",
    "alpha3": "MAR",
    "numeric": "504",
    "name": "Morocco",
    "nativeName": "المغرب",
    "aliases": [],
    "emoji": "🇲🇦",
    "callingCodes": [
      "+212"
    ],
    "continent": "AF",
    "capital": "Rabat",
    "currencies": [
      "MAD"
    ],
    "languages": [
      "ar"
    ]
  },
  {
    "code": "mz",
    "alpha2": "MZ",
    "alpha3": "MOZ",
    "numeric": "508",
    "name": "Mozambique",
    "nativeName": "Moçambique",
    "aliases": [],
    "emoji": "🇲🇿",
    "callingCodes": [
      "+258"
    ],
    "continent": "AF",
    "capital": "Maputo",
    "currencies": [
      "MZN"
    ],
    "languages": [
      "pt"
    ]
  },
  {
    "code": "mm",
    "alpha2": "MM",
    "alpha3": "MMR",
    "numeric": "104",
    "name": "Myanmar",
    "nativeName": "မြန်မာ",
    "aliases": [
      "Burma",
      "Myanmar (Burma)"
    ],
    "emoji": "🇲🇲",
    "callingCodes": [
      "+95"
    ],
    "continent": "AS",
    "capital": "Naypyidaw",
    "currencies": [
      "MMK"
    ],
    "languages": [
      "my"
    ]
  },
  {
    "code": "na",
    "alpha2": "NA",
    "alpha3": "NAM",
    "numeric": "516",
    "name": "Namibia",
    "nativeName": "Namibia",
    "aliases": [
      "South West Africa"
    ],
    "emoji": "🇳🇦",
    "callingCodes": [
      "+264"
    ],
    "continent": "AF",
    "capital": "Windhoek",
    "currencies": [
      "NAD",
      "ZAR"
    ],
    "languages": [
      "en",
      "af"
    ]
  },
  {
    "code": "nr",
    "alpha2": "NR",
    "alpha3": "NRU",
    "numeric": "520",
    "name": "Nauru",
    "nativeName": "Nauru",
    "aliases": [],
    "emoji": "🇳🇷",
    "callingCodes": [
      "+674"
    ],
    "continent": "OC",
    "capital": "Yaren",
    "currencies": [
      "AUD"
    ],
    "languages": [
      "en",
      "na"
    ]
  },
  {
    "code": "np",
    "alpha2": "NP",
    "alpha3": "NPL",
    "numeric": "524",
    "name": "Nepal",
    "nativeName": "नेपाल",
    "aliases": [],
    "emoji": "🇳🇵",
    "callingCodes": [
      "+977"
    ],
    "continent": "AS",
    "capital": "Kathmandu",
    "currencies": [
      "NPR"
    ],
    "languages": [
      "ne"
    ]
  },
  {
    "code": "nl",
    "alpha2": "NL",
    "alpha3": "NLD",
    "numeric": "528",
    "name": "Netherlands",
    "nativeName": "Nederland",
    "aliases": [
      "Holland"
    ],
    "emoji": "🇳🇱",
    "callingCodes": [
      "+31"
    ],
    "continent": "EU",
    "capital": "Amsterdam",
    "currencies": [
      "EUR"
    ],
    "languages": [
      "nl"
    ]
  },
  {
    "code": "nc",
    "alpha2": "NC",
    "alpha3": "NCL",
    "numeric": "540",
    "name": "New Caledonia",
    "nativeName": "Nouvelle-Calédonie",
    "aliases": [],
    "emoji": "🇳🇨",
    "callingCodes": [
      "+687"
    ],
    "continent": "OC",
    "capital": "Nouméa",
    "currencies": [
      "XPF"
    ],
    "languages": [
      "fr"
    ]
  },
  {
    "code": "nz",
    "alpha2": "NZ",
    "alpha3": "NZL",
    "numeric": "554",
    "name": "New Zealand",
    "nativeName": "New Zealand",
    "aliases": [],
    "emoji": "🇳🇿",
    "callingCodes": [
      "+64"
    ],
    "continent": "OC",
    "capital": "Wellington",
    "currencies": [
      "NZD"
    ],
    "languages": [
      "en",
      "mi"
    ]
  },
  {
    "code": "ni",
    "alpha2": "NI",
    "alpha3": "NIC",
    "numeric": "558",
    "name": "Nicaragua",
    "nativeName": "Nicaragua",
    "aliases": [],
    "emoji": "🇳🇮",
    "callingCodes": [
      "+505"
    ],
    "continent": "NA",
    "capital": "Managua",
    "currencies": [
      "NIO"
    ],
    "languages": [
      "es"
    ]
  },
  {
    "code": "ne",
    "alpha2": "NE",
    "alpha3": "NER",
    "numeric": "562",
    "name": "Niger",
    "nativeName": "Niger",
    "aliases": [],
    "emoji": "🇳🇪",
    "callingCodes": [
      "+227"
    ],
    "continent": "AF",
    "capital": "Niamey",
    "currencies": [
      "XOF"
    ],
    "languages": [
      "fr"
    ]
  },
  {
    "code": "ng",
    "alpha2": "NG",
    "alpha3": "NGA",
    "numeric": "566",
    "name": "Nigeria",
    "nativeName": "Nigeria",
    "aliases": [],
    "emoji": "🇳🇬",
    "callingCodes": [
      "+234"
    ],
    "continent": "AF",
    "capital": "Abuja",
    "currencies": [
      "NGN"
    ],
    "languages": [
      "en"
    ]
  },
  {
    "code": "nu",
    "alpha2": "NU",
    "alpha3": "NIU",
    "numeric": "570",
    "name": "Niue",
    "nativeName": "Niuē",
    "aliases": [],
    "emoji": "🇳🇺",
    "callingCodes": [
      "+683"
    ],
    "continent": "OC",
    "capital": "Alofi",
    "currencies": [
      "NZD"
    ],
    "languages": [
      "en"
    ]
  },
  {
    "code": "nf",
    "alpha2": "NF",
    "alpha3": "NFK",
    "numeric": "574",
    "name": "Norfolk Island",
    "nativeName": "Norfolk Island",
    "aliases": [],
    "emoji": "🇳🇫",
    "callingCodes": [
      "+672"
    ],
    "continent": "OC",
    "capital": "Kingston",
    "currencies": [
      "AUD"
    ],
    "languages": [
      "en"
    ]
  },
  {
    "code": "kp",
    "alpha2": "KP",
    "alpha3": "PRK",
    "numeric": "408",
    "name": "North Korea",
    "nativeName": "북한",
    "aliases": [
      "DPRK"
    ],
    "emoji": "🇰🇵",
    "callingCodes": [
      "+850"
    ],
    "continent": "AS",
    "capital": "Pyongyang",
    "currencies": [
      "KPW"
    ],
    "languages": [
      "ko"
    ]
  },
  {
    "code": "mk",
    "alpha2": "MK",
    "alpha3": "MKD",
    "numeric": "807",
    "name": "North Macedonia",
    "nativeName": "Северна Македонија",
    "aliases": [
      "Macedonia",
      "FYROM"
    ],
    "emoji": "🇲🇰",
    "callingCodes": [
      "+389"
    ],
    "continent": "EU",
    "capital": "Skopje",
    "currencies": [
      "MKD"
    ],
    "languages": [
      "mk"
    ]
  },
  {
    "code": "mp",
    "alpha2": "MP",
    "alpha3": "MNP",
    "numeric": "580",
    "name": "Northern Mariana Islands",
    "nativeName": "Northern Mariana Islands",
    "aliases": [],
    "emoji": "🇲🇵",
    "callingCodes": [
      "+1"
    ],
    "continent": "OC",
    "capital": "Saipan",
    "currencies": [
      "USD"
    ],
    "languages": [
      "en",
      "ch"
    ]
  },
  {
    "code": "no",
    "alpha2": "NO",
    "alpha3": "NOR",
    "numeric": "578",
    "name": "Norway",
    "nativeName": "Norge",
    "aliases": [],
    "emoji": "🇳🇴",
    "callingCodes": [
      "+47"
    ],
    "continent": "EU",
    "capital": "Oslo",
    "currencies": [
      "NOK"
    ],
    "languages": [
      "no",
      "nb",
      "nn"
    ]
  },
  {
    "code": "om",
    "alpha2": "OM",
    "alpha3": "OMN",
    "numeric": "512",
    "name": "Oman",
    "nativeName": "عمان",
    "aliases": [],
    "emoji": "🇴🇲",
    "callingCodes": [
      "+968"
    ],
    "continent": "AS",
    "capital": "Muscat",
    "currencies": [
      "OMR"
    ],
    "languages": [
      "ar"
    ]
  },
  {
    "code": "pk",
    "alpha2": "PK",
    "alpha3": "PAK",
    "numeric": "586",
    "name": "Pakistan",
    "nativeName": "Pakistan",
    "aliases": [],
    "emoji": "🇵🇰",
    "callingCodes": [
      "+92"
    ],
    "continent": "AS",
    "capital": "Islamabad",
    "currencies": [
      "PKR"
    ],
    "languages": [
      "en",
      "ur"
    ]
  },
  {
    "code": "pw",
    "alpha2": "PW",
    "alpha3": "PLW",
    "numeric": "585",
    "name": "Palau",
    "nativeName": "Palau",
    "aliases": [],
    "emoji": "🇵🇼",
    "callingCodes": [
      "+680"
    ],
    "continent": "OC",
    "capital": "Ngerulmud",
    "currencies": [
      "USD"
    ],
    "languages": [
      "en"
    ]
  },
  {
    "code": "ps",
    "alpha2": "PS",
    "alpha3": "PSE",
    "numeric": "275",
    "name": "Palestine",
    "nativeName": "فلسطين",
    "aliases": [],
    "emoji": "🇵🇸",
    "callingCodes": [
      "+970"
    ],
    "continent": "AS",
    "capital": "Ramallah",
    "currencies": [
      "ILS"
    ],
    "languages": [
      "ar"
    ]
  },
  {
    "code": "pa",
    "alpha2": "PA",
    "alpha3": "PAN",
    "numeric": "591",
    "name": "Panama",
    "nativeName": "Panamá",
    "aliases": [],
    "emoji": "🇵🇦",
    "callingCodes": [
      "+507"
    ],
    "continent": "NA",
    "capital": "Panama City",
    "currencies": [
      "PAB",
      "USD"
    ],
    "languages": [
      "es"
    ]
  },
  {
    "code": "pg",
    "alpha2": "PG",
    "alpha3": "PNG",
    "numeric": "598",
    "name": "Papua New Guinea",
    "nativeName": "Papua Niugini",
    "aliases": [],
    "emoji": "🇵🇬",
    "callingCodes": [
      "+675"
    ],
    "continent": "OC",
    "capital": "Port Moresby",
    "currencies": [
      "PGK"
    ],
    "languages": [
      "en"
    ]
  },
  {
    "code": "py",
    "alpha2": "PY",
    "alpha3": "PRY",
    "numeric": "600",
    "name": "Paraguay",
    "nativeName": "Paraguay",
    "aliases": [],
    "emoji": "🇵🇾",
    "callingCodes": [
      "+595"
    ],
    "continent": "SA",
    "capital": "Asunción",
    "currencies": [
      "PYG"
    ],
    "languages": [
      "es",
      "gn"
    ]
  },
  {
    "code": "pe",
    "alpha2": "PE",
    "alpha3": "PER",
    "numeric": "604",
    "name": "Peru",
    "nativeName": "Perú",
    "aliases": [],
    "emoji": "🇵🇪",
    "callingCodes": [
      "+51"
    ],
    "continent": "SA",
    "capital": "Lima",
    "currencies": [
      "PEN"
    ],
    "languages": [
      "es"
    ]
  },
  {
    "code": "ph",
    "alpha2": "PH",
    "alpha3": "PHL",
    "numeric": "608",
    "name": "Philippines",
    "nativeName": "Pilipinas",
    "aliases": [],
    "emoji": "🇵🇭",
    "callingCodes": [
      "+63"
    ],
    "continent": "AS",
    "capital": "Manila",
    "currencies": [
      "PHP"
    ],
    "languages": [
      "en",
      "tl"
    ]
  },
  {
    "code": "pn",
    "alpha2": "PN",
    "alpha3": "PCN",
    "numeric": "612",
    "name": "Pitcairn Islands",
    "nativeName": "Pitcairn Islands",
    "aliases": [],
    "emoji": "🇵🇳",
    "callingCodes": [
      "+64"
    ],
    "continent": "OC",
    "capital": "Adamstown",
    "currencies": [
      "NZD"
    ],
    "languages": [
      "en"
    ]
  },
  {
    "code": "pl",
    "alpha2": "PL",
    "alpha3": "POL",
    "numeric": "616",
    "name": "Poland",
    "nativeName": "Polska",
    "aliases": [],
    "emoji": "🇵🇱",
    "callingCodes": [
      "+48"
    ],
    "continent": "EU",
    "capital": "Warsaw",
    "currencies": [
      "PLN"
    ],
    "languages": [
      "pl"
    ]
  },
  {
    "code": "pt",
    "alpha2": "PT",
    "alpha3": "PRT",
    "numeric": "620",
    "name": "Portugal",
    "nativeName": "Portugal",
    "aliases": [],
    "emoji": "🇵🇹",
    "callingCodes": [
      "+351"
    ],
    "continent": "EU",
    "capital": "Lisbon",
    "currencies": [
      "EUR"
    ],
    "languages": [
      "pt"
    ]
  },
  {
    "code": "pr",
    "alpha2": "PR",
    "alpha3": "PRI",
    "numeric": "630",
    "name": "Puerto Rico",
    "nativeName": "Puerto Rico",
    "aliases": [],
    "emoji": "🇵🇷",
    "callingCodes": [
      "+1"
    ],
    "continent": "NA",
    "capital": "San Juan",
    "currencies": [
      "USD"
    ],
    "languages": [
      "es",
      "en"
    ]
  },
  {
    "code": "qa",
    "alpha2": "QA",
    "alpha3": "QAT",
    "numeric": "634",
    "name": "Qatar",
    "nativeName": "قطر",
    "aliases": [],
    "emoji": "🇶🇦",
    "callingCodes": [
      "+974"
    ],
    "continent": "AS",
    "capital": "Doha",
    "currencies": [
      "QAR"
    ],
    "languages": [
      "ar"
    ]
  },
  {
    "code": "cg",
    "alpha2": "CG",
    "alpha3": "COG",
    "numeric": "178",
    "name": "Republic of the Congo",
    "nativeName": "République du Congo",
    "aliases": [
      "Congo-Brazzaville"
    ],
    "emoji": "🇨🇬",
    "callingCodes": [
      "+242"
    ],
    "continent": "AF",
    "capital": "Brazzaville",
    "currencies": [
      "XAF"
    ],
    "languages": [
      "fr",
      "ln"
    ]
  },
  {
    "code": "re",
    "alpha2": "RE",
    "alpha3": "REU",
    "numeric": "638",
    "name": "Reunion",
    "nativeName": "La Réunion",
    "aliases": [],
    "emoji": "🇷🇪",
    "callingCodes": [
      "+262"
    ],
    "continent": "AF",
    "capital": "Saint-Denis",
    "currencies": [
      "EUR"
    ],
    "languages": [
      "fr"
    ]
  },
  {
    "code": "ro",
    "alpha2": "RO",
    "alpha3": "ROU",
    "numeric": "642",
    "name": "Romania",
    "nativeName": "România",
    "aliases": [
      "Rumania",
      "Roumania"
    ],
    "emoji": "🇷🇴",
    "callingCodes": [
      "+40"
    ],
    "continent": "EU",
    "capital": "Bucharest",
    "currencies": [
      "RON"
    ],
    "languages": [
      "ro"
    ]
  },
  {
    "code": "ru",
    "alpha2": "RU",
    "alpha3": "RUS",
    "numeric": "643",
    "name": "Russia",
    "nativeName": "Россия",
    "aliases": [
      "Russian Federation"
    ],
    "emoji": "🇷🇺",
    "callingCodes": [
      "+7"
    ],
    "continent": "AS",
    "capital": "Moscow",
    "currencies": [
      "RUB"
    ],
    "languages": [
      "ru"
    ]
  },
  {
    "code": "rw",
    "alpha2": "RW",
    "alpha3": "RWA",
    "numeric": "646",
    "name": "Rwanda",
    "nativeName": "Rwanda",
    "aliases": [],
    "emoji": "🇷🇼",
    "callingCodes": [
      "+250"
    ],
    "continent": "AF",
    "capital": "Kigali",
    "currencies": [
      "RWF"
    ],
    "languages": [
      "rw",
      "en",
      "fr"
    ]
  },
  {
    "code": "bl",
    "alpha2": "BL",
    "alpha3": "BLM",
    "numeric": "652",
    "name": "Saint Barthelemy",
    "nativeName": "Saint-Barthélemy",
    "aliases": [],
    "emoji": "🇧🇱",
    "callingCodes": [
      "+590"
    ],
    "continent": "NA",
    "capital": "Gustavia",
    "currencies": [
      "EUR"
    ],
    "languages": [
      "fr"
    ]
  },
  {
    "code": "sh",
    "alpha2": "SH",
    "alpha3": "SHN",
    "numeric": "654",
    "name": "Saint Helena",
    "nativeName": "Saint Helena",
    "aliases": [],
    "emoji": "🇸🇭",
    "callingCodes": [
      "+290"
    ],
    "continent": "AF",
    "capital": "Jamestown",
    "currencies": [
      "SHP"
    ],
    "languages": [
      "en"
    ]
  },
  {
    "code": "kn",
    "alpha2": "KN",
    "alpha3": "KNA",
    "numeric": "659",
    "name": "Saint Kitts and Nevis",
    "nativeName": "Saint Kitts and Nevis",
    "aliases": [],
    "emoji": "🇰🇳",
    "callingCodes": [
      "+1"
    ],
    "continent": "NA",
    "capital": "Basseterre",
    "currencies": [
      "XCD"
    ],
    "languages": [
      "en"
    ]
  },
  {
    "code": "lc",
    "alpha2": "LC",
    "alpha3": "LCA",
    "numeric": "662",
    "name": "Saint Lucia",
    "nativeName": "Saint Lucia",
    "aliases": [],
    "emoji": "🇱🇨",
    "callingCodes": [
      "+1"
    ],
    "continent": "NA",
    "capital": "Castries",
    "currencies": [
      "XCD"
    ],
    "languages": [
      "en"
    ]
  },
  {
    "code": "mf",
    "alpha2": "MF",
    "alpha3": "MAF",
    "numeric": "663",
    "name": "Saint Martin",
    "nativeName": "Saint-Martin",
    "aliases": [],
    "emoji": "🇲🇫",
    "callingCodes": [
      "+590"
    ],
    "continent": "NA",
    "capital": "Marigot",
    "currencies": [
      "EUR"
    ],
    "languages": [
      "en",
      "fr",
      "nl"
    ]
  },
  {
    "code": "pm",
    "alpha2": "PM",
    "alpha3": "SPM",
    "numeric": "666",
    "name": "Saint Pierre and Miquelon",
    "nativeName": "Saint-Pierre-et-Miquelon",
    "aliases": [],
    "emoji": "🇵🇲",
    "callingCodes": [
      "+508"
    ],
    "continent": "NA",
    "capital": "Saint-Pierre",
    "currencies": [
      "EUR"
    ],
    "languages": [
      "fr"
    ]
  },
  {
    "code": "vc",
    "alpha2": "VC",
    "alpha3": "VCT",
    "numeric": "670",
    "name": "Saint Vincent and the Grenadines",
    "nativeName": "Saint Vincent and the Grenadines",
    "aliases": [],
    "emoji": "🇻🇨",
    "callingCodes": [
      "+1"
    ],
    "continent": "NA",
    "capital": "Kingstown",
    "currencies": [
      "XCD"
    ],
    "languages": [
      "en"
    ]
  },
  {
    "code": "ws",
    "alpha2": "WS",
    "alpha3": "WSM",
    "numeric": "882",
    "name": "Samoa",
    "nativeName": "Samoa",
    "aliases": [],
    "emoji": "🇼🇸",
    "callingCodes": [
      "+685"
    ],
    "continent": "OC",
    "capital": "Apia",
    "currencies": [
      "WST"
    ],
    "languages": [
      "sm",
      "en"
    ]
  },
  {
    "code": "sm",
    "alpha2": "SM",
    "alpha3": "SMR",
    "numeric": "674",
    "name": "San Marino",
    "nativeName": "San Marino",
    "aliases": [],
    "emoji": "🇸🇲",
    "callingCodes": [
      "+378"
    ],
    "continent": "EU",
    "capital": "City of San Marino",
    "currencies": [
      "EUR"
    ],
    "languages": [
      "it"
    ]
  },
  {
    "code": "st",
    "alpha2": "ST",
    "alpha3": "STP",
    "numeric": "678",
    "name": "Sao Tome and Principe",
    "nativeName": "São Tomé e Príncipe",
    "aliases": [],
    "emoji": "🇸🇹",
    "callingCodes": [
      "+239"
    ],
    "continent": "AF",
    "capital": "São Tomé",
    "currencies": [
      "STN"
    ],
    "languages": [
      "pt"
    ]
  },
  {
    "code": "sa",
    "alpha2": "SA",
    "alpha3": "SAU",
    "numeric": "682",
    "name": "Saudi Arabia",
    "nativeName": "المملكة العربية السعودية",
    "aliases": [],
    "emoji": "🇸🇦",
    "callingCodes": [
      "+966"
    ],
    "continent": "AS",
    "capital": "Riyadh",
    "currencies": [
      "SAR"
    ],
    "languages": [
      "ar"
    ]
  },
  {
    "code": "sn",
    "alpha2": "SN",
    "alpha3": "SEN",
    "numeric": "686",
    "name": "Senegal",
    "nativeName": "Sénégal",
    "aliases": [],
    "emoji": "🇸🇳",
    "callingCodes": [
      "+221"
    ],
    "continent": "AF",
    "capital": "Dakar",
    "currencies": [
      "XOF"
    ],
    "languages": [
      "fr"
    ]
  },
  {
    "code": "rs",
    "alpha2": "RS",
    "alpha3": "SRB",
    "numeric": "688",
    "name": "Serbia",
    "nativeName": "Србија",
    "aliases": [],
    "emoji": "🇷🇸",
    "callingCodes": [
      "+381"
    ],
    "continent": "EU",
    "capital": "Belgrade",
    "currencies": [
      "RSD"
    ],
    "languages": [
      "sr"
    ]
  },
  {
    "code": "sc",
    "alpha2": "SC",
    "alpha3": "SYC",
    "numeric": "690",
    "name": "Seychelles",
    "nativeName": "Seychelles",
    "aliases": [],
    "emoji": "🇸🇨",
    "callingCodes": [
      "+248"
    ],
    "continent": "AF",
    "capital": "Victoria",
    "currencies": [
      "SCR"
    ],
    "languages": [
      "fr",
      "en"
    ]
  },
  {
    "code": "sl",
    "alpha2": "SL",
    "alpha3": "SLE",
    "numeric": "694",
    "name": "Sierra Leone",
    "nativeName": "Sierra Leone",
    "aliases": [],
    "emoji": "🇸🇱",
    "callingCodes": [
      "+232"
    ],
    "continent": "AF",
    "capital": "Freetown",
    "currencies": [
      "SLE"
    ],
    "languages": [
      "en"
    ]
  },
  {
    "code": "sg",
    "alpha2": "SG",
    "alpha3": "SGP",
    "numeric": "702",
    "name": "Singapore",
    "nativeName": "Singapore",
    "aliases": [],
    "emoji": "🇸🇬",
    "callingCodes": [
      "+65"
    ],
    "continent": "AS",
    "capital": "Singapore",
    "currencies": [
      "SGD"
    ],
    "languages": [
      "en",
      "ms",
      "ta",
      "zh"
    ]
  },
  {
    "code": "sx",
    "alpha2": "SX",
    "alpha3": "SXM",
    "numeric": "534",
    "name": "Sint Maarten",
    "nativeName": "Sint Maarten",
    "aliases": [],
    "emoji": "🇸🇽",
    "callingCodes": [
      "+1"
    ],
    "continent": "NA",
    "capital": "Philipsburg",
    "currencies": [
      "XCG"
    ],
    "languages": [
      "nl",
      "en"
    ]
  },
  {
    "code": "sk",
    "alpha2": "SK",
    "alpha3": "SVK",
    "numeric": "703",
    "name": "Slovakia",
    "nativeName": "Slovensko",
    "aliases": [],
    "emoji": "🇸🇰",
    "callingCodes": [
      "+421"
    ],
    "continent": "EU",
    "capital": "Bratislava",
    "currencies": [
      "EUR"
    ],
    "languages": [
      "sk"
    ]
  },
  {
    "code": "si",
    "alpha2": "SI",
    "alpha3": "SVN",
    "numeric": "705",
    "name": "Slovenia",
    "nativeName": "Slovenija",
    "aliases": [],
    "emoji": "🇸🇮",
    "callingCodes": [
      "+386"
    ],
    "continent": "EU",
    "capital": "Ljubljana",
    "currencies": [
      "EUR"
    ],
    "languages": [
      "sl"
    ]
  },
  {
    "code": "sb",
    "alpha2": "SB",
    "alpha3": "SLB",
    "numeric": "090",
    "name": "Solomon Islands",
    "nativeName": "Solomon Islands",
    "aliases": [],
    "emoji": "🇸🇧",
    "callingCodes": [
      "+677"
    ],
    "continent": "OC",
    "capital": "Honiara",
    "currencies": [
      "SBD"
    ],
    "languages": [
      "en"
    ]
  },
  {
    "code": "so",
    "alpha2": "SO",
    "alpha3": "SOM",
    "numeric": "706",
    "name": "Somalia",
    "nativeName": "Soomaaliya",
    "aliases": [],
    "emoji": "🇸🇴",
    "callingCodes": [
      "+252"
    ],
    "continent": "AF",
    "capital": "Mogadishu",
    "currencies": [
      "SOS"
    ],
    "languages": [
      "so",
      "ar"
    ]
  },
  {
    "code": "za",
    "alpha2": "ZA",
    "alpha3": "ZAF",
    "numeric": "710",
    "name": "South Africa",
    "nativeName": "South Africa",
    "aliases": [],
    "emoji": "🇿🇦",
    "callingCodes": [
      "+27"
    ],
    "continent": "AF",
    "capital": "Pretoria",
    "currencies": [
      "ZAR"
    ],
    "languages": [
      "af",
      "en",
      "nr",
      "st",
      "ss",
      "tn",
      "ts",
      "ve",
      "xh",
      "zu"
    ]
  },
  {
    "code": "gs",
    "alpha2": "GS",
    "alpha3": "SGS",
    "numeric": "239",
    "name": "South Georgia and the South Sandwich Islands",
    "nativeName": "South Georgia",
    "aliases": [],
    "emoji": "🇬🇸",
    "callingCodes": [
      "+500"
    ],
    "continent": "AN",
    "capital": "King Edward Point",
    "currencies": [
      "GBP"
    ],
    "languages": [
      "en"
    ]
  },
  {
    "code": "kr",
    "alpha2": "KR",
    "alpha3": "KOR",
    "numeric": "410",
    "name": "South Korea",
    "nativeName": "대한민국",
    "aliases": [
      "Republic of Korea"
    ],
    "emoji": "🇰🇷",
    "callingCodes": [
      "+82"
    ],
    "continent": "AS",
    "capital": "Seoul",
    "currencies": [
      "KRW"
    ],
    "languages": [
      "ko"
    ]
  },
  {
    "code": "ss",
    "alpha2": "SS",
    "alpha3": "SSD",
    "numeric": "728",
    "name": "South Sudan",
    "nativeName": "South Sudan",
    "aliases": [],
    "emoji": "🇸🇸",
    "callingCodes": [
      "+211"
    ],
    "continent": "AF",
    "capital": "Juba",
    "currencies": [
      "SSP"
    ],
    "languages": [
      "en"
    ]
  },
  {
    "code": "es",
    "alpha2": "ES",
    "alpha3": "ESP",
    "numeric": "724",
    "name": "Spain",
    "nativeName": "España",
    "aliases": [],
    "emoji": "🇪🇸",
    "callingCodes": [
      "+34"
    ],
    "continent": "EU",
    "capital": "Madrid",
    "currencies": [
      "EUR"
    ],
    "languages": [
      "es",
      "eu",
      "ca",
      "gl",
      "oc"
    ]
  },
  {
    "code": "lk",
    "alpha2": "LK",
    "alpha3": "LKA",
    "numeric": "144",
    "name": "Sri Lanka",
    "nativeName": "śrī laṃkāva",
    "aliases": [
      "Ceylon"
    ],
    "emoji": "🇱🇰",
    "callingCodes": [
      "+94"
    ],
    "continent": "AS",
    "capital": "Colombo",
    "currencies": [
      "LKR"
    ],
    "languages": [
      "si",
      "ta"
    ]
  },
  {
    "code": "sd",
    "alpha2": "SD",
    "alpha3": "SDN",
    "numeric": "729",
    "name": "Sudan",
    "nativeName": "السودان",
    "aliases": [],
    "emoji": "🇸🇩",
    "callingCodes": [
      "+249"
    ],
    "continent": "AF",
    "capital": "Khartoum",
    "currencies": [
      "SDG"
    ],
    "languages": [
      "ar",
      "en"
    ]
  },
  {
    "code": "sr",
    "alpha2": "SR",
    "alpha3": "SUR",
    "numeric": "740",
    "name": "Suriname",
    "nativeName": "Suriname",
    "aliases": [],
    "emoji": "🇸🇷",
    "callingCodes": [
      "+597"
    ],
    "continent": "SA",
    "capital": "Paramaribo",
    "currencies": [
      "SRD"
    ],
    "languages": [
      "nl"
    ]
  },
  {
    "code": "sj",
    "alpha2": "SJ",
    "alpha3": "SJM",
    "numeric": "744",
    "name": "Svalbard and Jan Mayen",
    "nativeName": "Svalbard og Jan Mayen",
    "aliases": [],
    "emoji": "🇸🇯",
    "callingCodes": [
      "+47"
    ],
    "continent": "EU",
    "capital": "Longyearbyen",
    "currencies": [
      "NOK"
    ],
    "languages": [
      "no"
    ]
  },
  {
    "code": "se",
    "alpha2": "SE",
    "alpha3": "SWE",
    "numeric": "752",
    "name": "Sweden",
    "nativeName": "Sverige",
    "aliases": [],
    "emoji": "🇸🇪",
    "callingCodes": [
      "+46"
    ],
    "continent": "EU",
    "capital": "Stockholm",
    "currencies": [
      "SEK"
    ],
    "languages": [
      "sv"
    ]
  },
  {
    "code": "ch",
    "alpha2": "CH",
    "alpha3": "CHE",
    "numeric": "756",
    "name": "Switzerland",
    "nativeName": "Schweiz",
    "aliases": [],
    "emoji": "🇨🇭",
    "callingCodes": [
      "+41"
    ],
    "continent": "EU",
    "capital": "Bern",
    "currencies": [
      "CHF",
      "CHE",
      "CHW"
    ],
    "languages": [
      "de",
      "fr",
      "it"
    ]
  },
  {
    "code": "sy",
    "alpha2": "SY",
    "alpha3": "SYR",
    "numeric": "760",
    "name": "Syria",
    "nativeName": "سوريا",
    "aliases": [
      "Syrian Arab Republic"
    ],
    "emoji": "🇸🇾",
    "callingCodes": [
      "+963"
    ],
    "continent": "AS",
    "capital": "Damascus",
    "currencies": [
      "SYP"
    ],
    "languages": [
      "ar"
    ]
  },
  {
    "code": "tw",
    "alpha2": "TW",
    "alpha3": "TWN",
    "numeric": "158",
    "name": "Taiwan",
    "nativeName": "臺灣",
    "aliases": [
      "Formosa"
    ],
    "emoji": "🇹🇼",
    "callingCodes": [
      "+886"
    ],
    "continent": "AS",
    "capital": "Taipei",
    "currencies": [
      "TWD"
    ],
    "languages": [
      "zh"
    ]
  },
  {
    "code": "tj",
    "alpha2": "TJ",
    "alpha3": "TJK",
    "numeric": "762",
    "name": "Tajikistan",
    "nativeName": "Тоҷикистон",
    "aliases": [],
    "emoji": "🇹🇯",
    "callingCodes": [
      "+992"
    ],
    "continent": "AS",
    "capital": "Dushanbe",
    "currencies": [
      "TJS"
    ],
    "languages": [
      "tg",
      "ru"
    ]
  },
  {
    "code": "tz",
    "alpha2": "TZ",
    "alpha3": "TZA",
    "numeric": "834",
    "name": "Tanzania",
    "nativeName": "Tanzania",
    "aliases": [
      "Tanganyika"
    ],
    "emoji": "🇹🇿",
    "callingCodes": [
      "+255"
    ],
    "continent": "AF",
    "capital": "Dodoma",
    "currencies": [
      "TZS"
    ],
    "languages": [
      "sw",
      "en"
    ]
  },
  {
    "code": "th",
    "alpha2": "TH",
    "alpha3": "THA",
    "numeric": "764",
    "name": "Thailand",
    "nativeName": "ประเทศไทย",
    "aliases": [
      "Siam"
    ],
    "emoji": "🇹🇭",
    "callingCodes": [
      "+66"
    ],
    "continent": "AS",
    "capital": "Bangkok",
    "currencies": [
      "THB"
    ],
    "languages": [
      "th"
    ]
  },
  {
    "code": "tg",
    "alpha2": "TG",
    "alpha3": "TGO",
    "numeric": "768",
    "name": "Togo",
    "nativeName": "Togo",
    "aliases": [],
    "emoji": "🇹🇬",
    "callingCodes": [
      "+228"
    ],
    "continent": "AF",
    "capital": "Lomé",
    "currencies": [
      "XOF"
    ],
    "languages": [
      "fr"
    ]
  },
  {
    "code": "tk",
    "alpha2": "TK",
    "alpha3": "TKL",
    "numeric": "772",
    "name": "Tokelau",
    "nativeName": "Tokelau",
    "aliases": [],
    "emoji": "🇹🇰",
    "callingCodes": [
      "+690"
    ],
    "continent": "OC",
    "capital": "Fakaofo",
    "currencies": [
      "NZD"
    ],
    "languages": [
      "en"
    ]
  },
  {
    "code": "to",
    "alpha2": "TO",
    "alpha3": "TON",
    "numeric": "776",
    "name": "Tonga",
    "nativeName": "Tonga",
    "aliases": [],
    "emoji": "🇹🇴",
    "callingCodes": [
      "+676"
    ],
    "continent": "OC",
    "capital": "Nuku'alofa",
    "currencies": [
      "TOP"
    ],
    "languages": [
      "en",
      "to"
    ]
  },
  {
    "code": "tt",
    "alpha2": "TT",
    "alpha3": "TTO",
    "numeric": "780",
    "name": "Trinidad and Tobago",
    "nativeName": "Trinidad and Tobago",
    "aliases": [],
    "emoji": "🇹🇹",
    "callingCodes": [
      "+1"
    ],
    "continent": "NA",
    "capital": "Port of Spain",
    "currencies": [
      "TTD"
    ],
    "languages": [
      "en"
    ]
  },
  {
    "code": "tn",
    "alpha2": "TN",
    "alpha3": "TUN",
    "numeric": "788",
    "name": "Tunisia",
    "nativeName": "تونس",
    "aliases": [],
    "emoji": "🇹🇳",
    "callingCodes": [
      "+216"
    ],
    "continent": "AF",
    "capital": "Tunis",
    "currencies": [
      "TND"
    ],
    "languages": [
      "ar"
    ]
  },
  {
    "code": "tr",
    "alpha2": "TR",
    "alpha3": "TUR",
    "numeric": "792",
    "name": "Türkiye",
    "nativeName": "Türkiye",
    "aliases": [
      "Turkey",
      "Turkiye"
    ],
    "emoji": "🇹🇷",
    "callingCodes": [
      "+90"
    ],
    "continent": "AS",
    "capital": "Ankara",
    "currencies": [
      "TRY"
    ],
    "languages": [
      "tr"
    ]
  },
  {
    "code": "tm",
    "alpha2": "TM",
    "alpha3": "TKM",
    "numeric": "795",
    "name": "Turkmenistan",
    "nativeName": "Türkmenistan",
    "aliases": [
      "Turkmenia"
    ],
    "emoji": "🇹🇲",
    "callingCodes": [
      "+993"
    ],
    "continent": "AS",
    "capital": "Ashgabat",
    "currencies": [
      "TMT"
    ],
    "languages": [
      "tk",
      "ru"
    ]
  },
  {
    "code": "tc",
    "alpha2": "TC",
    "alpha3": "TCA",
    "numeric": "796",
    "name": "Turks and Caicos Islands",
    "nativeName": "Turks and Caicos Islands",
    "aliases": [],
    "emoji": "🇹🇨",
    "callingCodes": [
      "+1"
    ],
    "continent": "NA",
    "capital": "Cockburn Town",
    "currencies": [
      "USD"
    ],
    "languages": [
      "en"
    ]
  },
  {
    "code": "tv",
    "alpha2": "TV",
    "alpha3": "TUV",
    "numeric": "798",
    "name": "Tuvalu",
    "nativeName": "Tuvalu",
    "aliases": [
      "Ellice Islands"
    ],
    "emoji": "🇹🇻",
    "callingCodes": [
      "+688"
    ],
    "continent": "OC",
    "capital": "Funafuti",
    "currencies": [
      "AUD"
    ],
    "languages": [
      "en"
    ]
  },
  {
    "code": "um",
    "alpha2": "UM",
    "alpha3": "UMI",
    "numeric": "581",
    "name": "U.S. Minor Outlying Islands",
    "nativeName": "United States Minor Outlying Islands",
    "aliases": [],
    "emoji": "🇺🇲",
    "callingCodes": [
      "+1"
    ],
    "continent": "OC",
    "capital": "",
    "currencies": [
      "USD"
    ],
    "languages": [
      "en"
    ]
  },
  {
    "code": "vi",
    "alpha2": "VI",
    "alpha3": "VIR",
    "numeric": "850",
    "name": "U.S. Virgin Islands",
    "nativeName": "United States Virgin Islands",
    "aliases": [],
    "emoji": "🇻🇮",
    "callingCodes": [
      "+1"
    ],
    "continent": "NA",
    "capital": "Charlotte Amalie",
    "currencies": [
      "USD"
    ],
    "languages": [
      "en"
    ]
  },
  {
    "code": "ug",
    "alpha2": "UG",
    "alpha3": "UGA",
    "numeric": "800",
    "name": "Uganda",
    "nativeName": "Uganda",
    "aliases": [],
    "emoji": "🇺🇬",
    "callingCodes": [
      "+256"
    ],
    "continent": "AF",
    "capital": "Kampala",
    "currencies": [
      "UGX"
    ],
    "languages": [
      "en",
      "sw"
    ]
  },
  {
    "code": "ua",
    "alpha2": "UA",
    "alpha3": "UKR",
    "numeric": "804",
    "name": "Ukraine",
    "nativeName": "Україна",
    "aliases": [],
    "emoji": "🇺🇦",
    "callingCodes": [
      "+380"
    ],
    "continent": "EU",
    "capital": "Kyiv",
    "currencies": [
      "UAH"
    ],
    "languages": [
      "uk"
    ]
  },
  {
    "code": "ae",
    "alpha2": "AE",
    "alpha3": "ARE",
    "numeric": "784",
    "name": "United Arab Emirates",
    "nativeName": "دولة الإمارات العربية المتحدة",
    "aliases": [
      "UAE",
      "Emirates"
    ],
    "emoji": "🇦🇪",
    "callingCodes": [
      "+971"
    ],
    "continent": "AS",
    "capital": "Abu Dhabi",
    "currencies": [
      "AED"
    ],
    "languages": [
      "ar"
    ]
  },
  {
    "code": "gb",
    "alpha2": "GB",
    "alpha3": "GBR",
    "numeric": "826",
    "name": "United Kingdom",
    "nativeName": "United Kingdom",
    "aliases": [
      "UK",
      "Britain",
      "Great Britain"
    ],
    "emoji": "🇬🇧",
    "callingCodes": [
      "+44"
    ],
    "continent": "EU",
    "capital": "London",
    "currencies": [
      "GBP"
    ],
    "languages": [
      "en"
    ]
  },
  {
    "code": "us",
    "alpha2": "US",
    "alpha3": "USA",
    "numeric": "840",
    "name": "United States",
    "nativeName": "United States",
    "aliases": [
      "US",
      "USA",
      "America",
      "United States of America"
    ],
    "emoji": "🇺🇸",
    "callingCodes": [
      "+1"
    ],
    "continent": "NA",
    "capital": "Washington D.C.",
    "currencies": [
      "USD",
      "USN"
    ],
    "languages": [
      "en"
    ]
  },
  {
    "code": "uy",
    "alpha2": "UY",
    "alpha3": "URY",
    "numeric": "858",
    "name": "Uruguay",
    "nativeName": "Uruguay",
    "aliases": [],
    "emoji": "🇺🇾",
    "callingCodes": [
      "+598"
    ],
    "continent": "SA",
    "capital": "Montevideo",
    "currencies": [
      "UYU",
      "UYI"
    ],
    "languages": [
      "es"
    ]
  },
  {
    "code": "uz",
    "alpha2": "UZ",
    "alpha3": "UZB",
    "numeric": "860",
    "name": "Uzbekistan",
    "nativeName": "O'zbekiston",
    "aliases": [],
    "emoji": "🇺🇿",
    "callingCodes": [
      "+998"
    ],
    "continent": "AS",
    "capital": "Tashkent",
    "currencies": [
      "UZS"
    ],
    "languages": [
      "uz",
      "ru"
    ]
  },
  {
    "code": "vu",
    "alpha2": "VU",
    "alpha3": "VUT",
    "numeric": "548",
    "name": "Vanuatu",
    "nativeName": "Vanuatu",
    "aliases": [
      "New Hebrides"
    ],
    "emoji": "🇻🇺",
    "callingCodes": [
      "+678"
    ],
    "continent": "OC",
    "capital": "Port Vila",
    "currencies": [
      "VUV"
    ],
    "languages": [
      "bi",
      "en",
      "fr"
    ]
  },
  {
    "code": "va",
    "alpha2": "VA",
    "alpha3": "VAT",
    "numeric": "336",
    "name": "Vatican City",
    "nativeName": "Vaticano",
    "aliases": [
      "Holy See",
      "Vatican"
    ],
    "emoji": "🇻🇦",
    "callingCodes": [
      "+39"
    ],
    "continent": "EU",
    "capital": "Vatican City",
    "currencies": [
      "EUR"
    ],
    "languages": [
      "it",
      "la"
    ]
  },
  {
    "code": "ve",
    "alpha2": "VE",
    "alpha3": "VEN",
    "numeric": "862",
    "name": "Venezuela",
    "nativeName": "Venezuela",
    "aliases": [],
    "emoji": "🇻🇪",
    "callingCodes": [
      "+58"
    ],
    "continent": "SA",
    "capital": "Caracas",
    "currencies": [
      "VES"
    ],
    "languages": [
      "es"
    ]
  },
  {
    "code": "vn",
    "alpha2": "VN",
    "alpha3": "VNM",
    "numeric": "704",
    "name": "Vietnam",
    "nativeName": "Việt Nam",
    "aliases": [
      "Viet Nam"
    ],
    "emoji": "🇻🇳",
    "callingCodes": [
      "+84"
    ],
    "continent": "AS",
    "capital": "Hanoi",
    "currencies": [
      "VND"
    ],
    "languages": [
      "vi"
    ]
  },
  {
    "code": "wf",
    "alpha2": "WF",
    "alpha3": "WLF",
    "numeric": "876",
    "name": "Wallis and Futuna",
    "nativeName": "Wallis et Futuna",
    "aliases": [],
    "emoji": "🇼🇫",
    "callingCodes": [
      "+681"
    ],
    "continent": "OC",
    "capital": "Mata-Utu",
    "currencies": [
      "XPF"
    ],
    "languages": [
      "fr"
    ]
  },
  {
    "code": "eh",
    "alpha2": "EH",
    "alpha3": "ESH",
    "numeric": "732",
    "name": "Western Sahara",
    "nativeName": "الصحراء الغربية",
    "aliases": [
      "Spanish Sahara"
    ],
    "emoji": "🇪🇭",
    "callingCodes": [
      "+212"
    ],
    "continent": "AF",
    "capital": "El Aaiún",
    "currencies": [
      "MAD",
      "DZD",
      "MRU"
    ],
    "languages": [
      "es"
    ]
  },
  {
    "code": "ye",
    "alpha2": "YE",
    "alpha3": "YEM",
    "numeric": "887",
    "name": "Yemen",
    "nativeName": "اليَمَن",
    "aliases": [],
    "emoji": "🇾🇪",
    "callingCodes": [
      "+967"
    ],
    "continent": "AS",
    "capital": "Sana'a",
    "currencies": [
      "YER"
    ],
    "languages": [
      "ar"
    ]
  },
  {
    "code": "zm",
    "alpha2": "ZM",
    "alpha3": "ZMB",
    "numeric": "894",
    "name": "Zambia",
    "nativeName": "Zambia",
    "aliases": [
      "Northern Rhodesia"
    ],
    "emoji": "🇿🇲",
    "callingCodes": [
      "+260"
    ],
    "continent": "AF",
    "capital": "Lusaka",
    "currencies": [
      "ZMW"
    ],
    "languages": [
      "en"
    ]
  },
  {
    "code": "zw",
    "alpha2": "ZW",
    "alpha3": "ZWE",
    "numeric": "716",
    "name": "Zimbabwe",
    "nativeName": "Zimbabwe",
    "aliases": [
      "Rhodesia",
      "Southern Rhodesia"
    ],
    "emoji": "🇿🇼",
    "callingCodes": [
      "+263"
    ],
    "continent": "AF",
    "capital": "Harare",
    "currencies": [
      "ZWG",
      "USD",
      "ZAR",
      "BWP",
      "GBP",
      "AUD",
      "CNY",
      "INR",
      "JPY"
    ],
    "languages": [
      "en",
      "sn",
      "nd"
    ]
  }
] as const

export const phoneCountryCodes = [
  "af",
  "ax",
  "al",
  "dz",
  "as",
  "ad",
  "ao",
  "ai",
  "ag",
  "ar",
  "am",
  "aw",
  "au",
  "at",
  "az",
  "bs",
  "bh",
  "bd",
  "bb",
  "by",
  "be",
  "bz",
  "bj",
  "bm",
  "bt",
  "bo",
  "bq",
  "ba",
  "bw",
  "br",
  "io",
  "vg",
  "bn",
  "bg",
  "bf",
  "bi",
  "cv",
  "kh",
  "cm",
  "ca",
  "ky",
  "cf",
  "td",
  "cl",
  "cn",
  "cx",
  "cc",
  "co",
  "km",
  "ck",
  "cr",
  "hr",
  "cu",
  "cw",
  "cy",
  "cz",
  "cd",
  "dk",
  "dj",
  "dm",
  "do",
  "tl",
  "ec",
  "eg",
  "sv",
  "gq",
  "er",
  "ee",
  "sz",
  "et",
  "fk",
  "fo",
  "fj",
  "fi",
  "fr",
  "gf",
  "pf",
  "ga",
  "gm",
  "ge",
  "de",
  "gh",
  "gi",
  "gr",
  "gl",
  "gd",
  "gp",
  "gu",
  "gt",
  "gg",
  "gn",
  "gw",
  "gy",
  "ht",
  "hn",
  "hk",
  "hu",
  "is",
  "in",
  "id",
  "ir",
  "iq",
  "ie",
  "im",
  "il",
  "it",
  "ci",
  "jm",
  "jp",
  "je",
  "jo",
  "kz",
  "ke",
  "ki",
  "xk",
  "kw",
  "kg",
  "la",
  "lv",
  "lb",
  "ls",
  "lr",
  "ly",
  "li",
  "lt",
  "lu",
  "mo",
  "mg",
  "mw",
  "my",
  "mv",
  "ml",
  "mt",
  "mh",
  "mq",
  "mr",
  "mu",
  "yt",
  "mx",
  "fm",
  "md",
  "mc",
  "mn",
  "me",
  "ms",
  "ma",
  "mz",
  "mm",
  "na",
  "nr",
  "np",
  "nl",
  "nc",
  "nz",
  "ni",
  "ne",
  "ng",
  "nu",
  "nf",
  "kp",
  "mk",
  "mp",
  "no",
  "om",
  "pk",
  "pw",
  "ps",
  "pa",
  "pg",
  "py",
  "pe",
  "ph",
  "pl",
  "pt",
  "pr",
  "qa",
  "cg",
  "re",
  "ro",
  "ru",
  "rw",
  "bl",
  "sh",
  "kn",
  "lc",
  "mf",
  "pm",
  "vc",
  "ws",
  "sm",
  "st",
  "sa",
  "sn",
  "rs",
  "sc",
  "sl",
  "sg",
  "sx",
  "sk",
  "si",
  "sb",
  "so",
  "za",
  "kr",
  "ss",
  "es",
  "lk",
  "sd",
  "sr",
  "sj",
  "se",
  "ch",
  "sy",
  "tw",
  "tj",
  "tz",
  "th",
  "tg",
  "tk",
  "to",
  "tt",
  "tn",
  "tr",
  "tm",
  "tc",
  "tv",
  "vi",
  "ug",
  "ua",
  "ae",
  "gb",
  "us",
  "uy",
  "uz",
  "vu",
  "va",
  "ve",
  "vn",
  "wf",
  "eh",
  "ye",
  "zm",
  "zw"
] as const

export type Country = (typeof countryData)[number]
export type CountryCode = Country["code"]
export type PhoneCountryCode = (typeof phoneCountryCodes)[number]
export type CountryAlpha2 = Country["alpha2"]
export type CountryAlpha3 = Country["alpha3"]
