// SPDX-License-Identifier: MIT

// Generated by scripts/generate-country-data.mjs from countries-list,
// i18n-iso-countries, and libphonenumber-js. Do not edit by hand.

export const countryDataMeta = {
  "generated": true,
  "validated": true,
  "countryCount": 250,
  "phoneCountryCount": 243,
  "sources": {
    "countries": "countries-list@3.4.1",
    "iso": "i18n-iso-countries@7.14.0",
    "phone": "libphonenumber-js@1.13.11"
  }
} as const
